In [ ]:
import re
import requests
from urllib.parse import urljoin
import pandas as pd
import schedule
import time
from datetime import datetime, timedelta
import os
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.base import MIMEBase
from email import encoders
import dotenv

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)

logger = logging.getLogger(__name__)

logger.info("Script iniciado")

2026-03-12 16:40:48,514 | INFO | Script iniciado

*** Acesso a PoloTrial (API)

In [2]:
#ROTA GERAL
dotenv.load_dotenv(override=True)

logger.info("Iniciando sessão com a API")

session = requests.Session()

polotrial_url = os.getenv("POLOTRIAL_URL")

if not polotrial_url:
    logger.error("Variável de ambiente POLOTRIAL_URL não encontrada")
    raise ValueError("POLOTRIAL_URL não definida")

logger.info(f"URL da API carregada")

payload = {
    "nome": os.getenv("POLOTRIAL_USER"),
    "password": os.getenv("POLOTRIAL_PASSWORD")
}

headers = {
    "Content-Type": "application/json"
}

session_url = f"{polotrial_url}/sessions"

logger.info(f"Endpoint de login: {session_url}")

try:

    login_response = requests.post(
        session_url,
        json=payload,
        headers=headers,
        timeout=30
    )

    logger.info(f"Status login API: {login_response.status_code}")

    login_response.raise_for_status()

except Exception as e:
    logger.error(f"Erro na requisição de login: {e}")
    raise

auth_cookie = login_response.cookies.get("userId")

if not auth_cookie:
    logger.error("Cookie de autenticação não recebido")
    raise Exception("Falha na autenticação")

endpoint_headers = {
    "cookie": f"userId={auth_cookie}"
}

logger.info("Autenticação bem-sucedida. Cookie obtido.")

# Mensagem de sucesso na optenção do cookie
if endpoint_headers['cookie']:
    logger.info("Autenticação bem-sucedida. Cookie obtido.")
    print(endpoint_headers)
    print(polotrial_url)
else:
    logger.error("Falha na autenticação. Verifique suas credenciais.")

2026-03-12 16:40:48,530 | INFO | Iniciando sessão com a API
2026-03-12 16:40:48,532 | INFO | URL da API carregada
2026-03-12 16:40:48,533 | INFO | Endpoint de login: https://api.polotrial.com/beta/sessions
2026-03-12 16:40:49,535 | INFO | Status login API: 200
2026-03-12 16:40:49,536 | INFO | Autenticação bem-sucedida. Cookie obtido.
2026-03-12 16:40:49,538 | INFO | Autenticação bem-sucedida. Cookie obtido.

{'cookie': 'userId=s%3Ax3dilBfhnmP4L_nHapMeVKi7rP1QZaMp.ENzQ4IuWzmWZg92JDK0iHZ%2Fva%2FXISqiK%2FuFEcECkqFU'}
https://api.polotrial.com/beta

In [3]:
protocolo_url = f"{polotrial_url}/protocolo"

logger.info("Iniciando coleta de protocolos ativos")

protocolos_ativos = [
    "161",  # Aguardando iniciação
    "39",   # Recrutamento aberto
    "9236", # Recrutamento aberto
    "9263", # Aguardando Ativação do Centro
    "393",  # Aguardando Ativação do Centro
    "9294", # Fase Contratual
    "819",  # Aguardando o Pacote Regulatório
    "739",  # Aprovação Anvisa
    "6",    # Aprovação Regulatória
    "912",  # Em apreciação ética
    "9163"  # Aprovado pelo CEP
]

df_protocolos = []

for co_status in protocolos_ativos:

    logger.info(f"Consultando protocolos com status {co_status}")

    query_params = {
        "nested": "true",
        "status_protocolo": co_status
    }

    try:

        response = requests.get(
            protocolo_url,
            headers=endpoint_headers,
            params=query_params,
            timeout=30
        )

        logger.info(
            f"Status {co_status} | HTTP {response.status_code}"
        )

        response.raise_for_status()

        protocolo_json = response.json()

        if not protocolo_json:
            logger.warning(
                f"Nenhum protocolo retornado para status {co_status}"
            )
            continue

        if isinstance(protocolo_json, dict):
            protocolo_json = [protocolo_json]

        df_temp = pd.DataFrame(protocolo_json)

        logger.info(
            f"{len(df_temp)} protocolos encontrados para status {co_status}"
        )

        df_protocolos.append(df_temp)

    except Exception as e:

        logger.error(
            f"Erro ao buscar protocolos para status {co_status}: {e}"
        )

if df_protocolos:

    protocolos_dataframe = pd.concat(
        df_protocolos,
        ignore_index=True
    )

    logger.info(
        f"DataFrame final de protocolos criado com "
        f"{len(protocolos_dataframe)} registros"
    )

else:

    logger.warning(
        "Nenhum protocolo retornado pela API para os status consultados"
    )

2026-03-12 16:40:49,552 | INFO | Iniciando coleta de protocolos ativos
2026-03-12 16:40:49,553 | INFO | Consultando protocolos com status 161
2026-03-12 16:40:50,358 | INFO | Status 161 | HTTP 200
2026-03-12 16:40:50,358 | WARNING | Nenhum protocolo retornado para status 161
2026-03-12 16:40:50,359 | INFO | Consultando protocolos com status 39
2026-03-12 16:40:51,165 | INFO | Status 39 | HTTP 200
2026-03-12 16:40:51,171 | INFO | 8 protocolos encontrados para status 39
2026-03-12 16:40:51,171 | INFO | Consultando protocolos com status 9236
2026-03-12 16:40:52,076 | INFO | Status 9236 | HTTP 200
2026-03-12 16:40:52,081 | INFO | 7 protocolos encontrados para status 9236
2026-03-12 16:40:52,082 | INFO | Consultando protocolos com status 9263
2026-03-12 16:40:52,849 | INFO | Status 9263 | HTTP 200
2026-03-12 16:40:52,854 | INFO | 1 protocolos encontrados para status 9263
2026-03-12 16:40:52,855 | INFO | Consultando protocolos com status 393
2026-03-12 16:40:53,600 | INFO | Status 393 | HTTP 200
2026-03-12 16:40:53,603 | INFO | 1 protocolos encontrados para status 393
2026-03-12 16:40:53,604 | INFO | Consultando protocolos com status 9294
2026-03-12 16:40:54,388 | INFO | Status 9294 | HTTP 200
2026-03-12 16:40:54,392 | INFO | 5 protocolos encontrados para status 9294
2026-03-12 16:40:54,393 | INFO | Consultando protocolos com status 819
2026-03-12 16:40:55,155 | INFO | Status 819 | HTTP 200
2026-03-12 16:40:55,157 | WARNING | Nenhum protocolo retornado para status 819
2026-03-12 16:40:55,158 | INFO | Consultando protocolos com status 739
2026-03-12 16:40:55,893 | INFO | Status 739 | HTTP 200
2026-03-12 16:40:55,893 | WARNING | Nenhum protocolo retornado para status 739
2026-03-12 16:40:55,894 | INFO | Consultando protocolos com status 6
2026-03-12 16:40:56,672 | INFO | Status 6 | HTTP 200
2026-03-12 16:40:56,673 | WARNING | Nenhum protocolo retornado para status 6
2026-03-12 16:40:56,674 | INFO | Consultando protocolos com status 912
2026-03-12 16:40:57,481 | INFO | Status 912 | HTTP 200
2026-03-12 16:40:57,486 | INFO | 7 protocolos encontrados para status 912
2026-03-12 16:40:57,486 | INFO | Consultando protocolos com status 9163
2026-03-12 16:40:58,271 | INFO | Status 9163 | HTTP 200
2026-03-12 16:40:58,282 | INFO | 3 protocolos encontrados para status 9163
2026-03-12 16:40:58,290 | INFO | DataFrame final de protocolos criado com 32 registros

In [4]:
#ROTA PESSOAS
pessoas_url = f"{polotrial_url}/pessoas"

logger.info("Iniciando coleta de pessoas")

query_params = {
    "nested": "true",
}

try:

    response = requests.get(
        pessoas_url,
        headers=endpoint_headers,
        params=query_params,
        timeout=30
    )

    logger.info(f"Status rota pessoas: {response.status_code}")

    response.raise_for_status()

    pessoas = response.json()

    if not pessoas:
        logger.warning("API retornou lista de pessoas vazia")

    pessoas_df = pd.DataFrame(pessoas)

    logger.info(
        f"DataFrame de pessoas criado com {len(pessoas_df)} registros"
    )

    logger.info(
        f"Colunas disponíveis: {pessoas_df.columns.tolist()}"
    )

except Exception as e:

    logger.error(f"Erro ao consultar rota pessoas: {e}")
    raise

2026-03-12 16:40:58,301 | INFO | Iniciando coleta de pessoas
2026-03-12 16:41:00,036 | INFO | Status rota pessoas: 200
2026-03-12 16:41:00,087 | INFO | DataFrame de pessoas criado com 3894 registros
2026-03-12 16:41:00,091 | INFO | Colunas disponíveis: ['dados_ativo', 'id', 'ds_nome', 'co_tipo_gn', 'co_equipe_gn', 'co_formacao_maior_nivel_gn', 'dt_ultimo_certificado_gcp', 'registro_profissional', 'declaracao_confidencialidade', 'custo_mensal_estimado', 'co_centro', 'equipe_padrao', 'equipe_padrao_kits', 'equipe_padrao_farmacia', 'equipe_padrao_naocega', 'filter', 'prox_vencimento_treinamento', 'co_especialidade', 'ativo', 'deleted', 'status', 'dados_co_tipo_gn', 'dados_co_equipe_gn', 'dados_co_formacao_maior_nivel_gn', 'dados_status', 'dados_centro', 'dados_equipe_padrao_farmacia', 'dados_equipe_padrao_kits', 'dados_equipe_padrao', 'dados_pessoa_especialidade']

In [5]:
logger.info(f"Shape dataframe pessoas: {pessoas_df.shape}")
logger.info(f"Colunas dataframe pessoas: {pessoas_df.columns.tolist()}")
logger.info("Primeiras linhas do dataframe pessoas:")
logger.info(f"\n{pessoas_df.head()}")

2026-03-12 16:41:00,099 | INFO | Shape dataframe pessoas: (3894, 30)
2026-03-12 16:41:00,100 | INFO | Colunas dataframe pessoas: ['dados_ativo', 'id', 'ds_nome', 'co_tipo_gn', 'co_equipe_gn', 'co_formacao_maior_nivel_gn', 'dt_ultimo_certificado_gcp', 'registro_profissional', 'declaracao_confidencialidade', 'custo_mensal_estimado', 'co_centro', 'equipe_padrao', 'equipe_padrao_kits', 'equipe_padrao_farmacia', 'equipe_padrao_naocega', 'filter', 'prox_vencimento_treinamento', 'co_especialidade', 'ativo', 'deleted', 'status', 'dados_co_tipo_gn', 'dados_co_equipe_gn', 'dados_co_formacao_maior_nivel_gn', 'dados_status', 'dados_centro', 'dados_equipe_padrao_farmacia', 'dados_equipe_padrao_kits', 'dados_equipe_padrao', 'dados_pessoa_especialidade']
2026-03-12 16:41:00,101 | INFO | Primeiras linhas do dataframe pessoas:
2026-03-12 16:41:00,106 | INFO |
            dados_ativo    id                 ds_nome  co_tipo_gn  \
0  {'descricao': 'Sim'}  2978                     NaN       562.0
1  {'descricao': 'Sim'}  3545                     NaN       562.0
2  {'descricao': 'Sim'}  1332                               649.0
3  {'descricao': 'Sim'}  3118   Alex Gonçalves Macedo       387.0
4  {'descricao': 'Sim'}  1554    Alex Vladimir Dudzic       649.0

  co_equipe_gn  co_formacao_maior_nivel_gn dt_ultimo_certificado_gcp  \
0         None                         NaN                       NaN
1         None                         NaN                       NaN
2         None                         NaN                       NaN
3         None                        31.0                2023-09-06
4         None                         NaN                       NaN

  registro_profissional declaracao_confidencialidade custo_mensal_estimado  \
0                   NaN                         None                  None
1                   NaN                         None                  None
2                   NaN                         None                  None
3             74.334/SP                         None                  None
4                   NaN                         None                  None

   ...  status                                   dados_co_tipo_gn  \
0  ...     NaN  {'id': 562, 'ds_descricao': 'Equipe padrão (ad...
1  ...     NaN  {'id': 562, 'ds_descricao': 'Equipe padrão (ad...
2  ...     NaN        {'id': 649, 'ds_descricao': 'Participante'}
3  ...  9404.0  {'id': 387, 'ds_descricao': 'Pesquisador Princ...
4  ...     NaN        {'id': 649, 'ds_descricao': 'Participante'}

   dados_co_equipe_gn        dados_co_formacao_maior_nivel_gn  \
0                None                                    None
1                None                                    None
2                None                                    None
3                None  {'id': 31, 'ds_descricao': 'Mestrado'}
4                None                                    None

                            dados_status  \
0                                   None
1                                   None
2                                   None
3  {'id': 9404, 'ds_descricao': 'Ativo'}
4                                   None

                                     dados_centro  \
0                                            None
1                                            None
2                                            None
3  {'id': 4, 'descricao': 'Santa Casa de Santos'}
4                                            None

  dados_equipe_padrao_farmacia  dados_equipe_padrao_kits  dados_equipe_padrao  \
0                         None                      None                 None
1                         None                      None                 None
2                         None                      None                 None
3                         None                      None                 None
4                         None                      None                 None

                          dados_pessoa_especialidade
0                                                 []
1                                                 []
2                                                 []
3  [{'id': 150, 'co_pessoa': 3118, 'co_pessoa_esp...
4                                                 []

[5 rows x 30 columns]

In [6]:
#ROTA AGENDA
agenda_url = f"{polotrial_url}/participante_visita"

logger.info("Iniciando coleta de agenda de participantes")

query_params = {
    "nested": "true",
}

try:
    response = requests.get(
        agenda_url,
        headers=endpoint_headers,
        params=query_params,
        timeout=30
    )

    logger.info(f"Status rota participante_visita: {response.status_code}")

    response.raise_for_status()

    agenda = response.json()

    if not agenda:
        logger.warning("API retornou agenda vazia")

    agenda_df = pd.DataFrame(agenda)

    logger.info(f"DataFrame agenda criado com {len(agenda_df)} registros")
    logger.info(f"Shape agenda_df: {agenda_df.shape}")
    logger.info(f"Colunas agenda_df: {agenda_df.columns.tolist()}")

    logger.info("Primeiras linhas da agenda:")
    logger.info(f"\n{agenda_df.head()}")

except Exception as e:
    logger.error(f"Erro ao consultar rota participante_visita: {e}")
    raise

2026-03-12 16:41:00,121 | INFO | Iniciando coleta de agenda de participantes
2026-03-12 16:41:08,015 | INFO | Status rota participante_visita: 200
2026-03-12 16:41:08,461 | INFO | DataFrame agenda criado com 16947 registros
2026-03-12 16:41:08,463 | INFO | Shape agenda_df: (16947, 48)
2026-03-12 16:41:08,463 | INFO | Colunas agenda_df: ['id', 'co_participante', 'co_protocolo', 'moeda', 'co_coordenador', 'co_visita', 'status', 'nome_tarefa', 'color', 'url', 'title', 'visita_extra', 'data_estimada', 'data_estimada_fim', 'data_realizada', 'observacoes', 'valor_previsto', 'valor_pago', 'data_solicitacao_pagamento', 'data_pagamento', 'status_participante', 'filtro_dias', 'urgencia', 'dias_do_inicio', 'semestre', 'co_nota_fiscal', 'co_status_nota_fiscal_gn', 'local', 'intervalo', 'intervalo_referencia', 'soma_procedimentos_prevista', 'soma_procedimentos_pago', 'soma_procedimentos_condicionais', 'procedimentos_extras', 'intervalo_unidade', 'data_ideal', 'data_preenchimento_visita', 'data_limite_min', 'data_limite_max', 'data_preenchimento_crf', 'data_monitorada', 'responsavel', 'dados_participante', 'dados_visita', 'dados_status', 'dados_nota_fiscal', 'dados_local', 'dados_responsavel']
2026-03-12 16:41:08,463 | INFO | Primeiras linhas da agenda:
2026-03-12 16:41:08,463 | INFO |
    id  co_participante  co_protocolo  moeda  co_coordenador  co_visita  \
0  639               54             4  568.0           261.0        1.0
1  640               56             4  568.0           261.0        1.0
2  641               57             4  568.0           261.0        1.0
3  642               58             4  568.0           261.0        1.0
4  643               59             4  568.0           261.0        1.0

   status nome_tarefa    color  \
0      20    Triagem   #330eb9
1      20    Triagem   #330eb9
2      20    Triagem   #330eb9
3      20    Triagem   #330eb9
4      20    Triagem   #330eb9

                                                 url  ... data_limite_max  \
0  ../participante_visita.php?operation=edit&pk0=639  ...             NaN
1  ../participante_visita.php?operation=edit&pk0=640  ...             NaN
2  ../participante_visita.php?operation=edit&pk0=641  ...             NaN
3  ../participante_visita.php?operation=edit&pk0=642  ...             NaN
4  ../participante_visita.php?operation=edit&pk0=643  ...             NaN

  data_preenchimento_crf data_monitorada responsavel  \
0                    NaN             NaN         NaN
1                    NaN             NaN         NaN
2                    NaN             NaN         NaN
3                    NaN             NaN         NaN
4                    NaN             NaN         NaN

                                  dados_participante  \
0  {'id': 54, 'co_protocolo': 4, 'id_participante...
1  {'id': 56, 'co_protocolo': 4, 'id_participante...
2  {'id': 57, 'co_protocolo': 4, 'id_participante...
3  {'id': 58, 'co_protocolo': 4, 'id_participante...
4  {'id': 59, 'co_protocolo': 4, 'id_participante...

                                        dados_visita  \
0  {'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...
1  {'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...
2  {'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...
3  {'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...
4  {'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...

                              dados_status  \
0  {'id': 20, 'ds_descricao': 'Realizada'}
1  {'id': 20, 'ds_descricao': 'Realizada'}
2  {'id': 20, 'ds_descricao': 'Realizada'}
3  {'id': 20, 'ds_descricao': 'Realizada'}
4  {'id': 20, 'ds_descricao': 'Realizada'}

                                   dados_nota_fiscal dados_local  \
0  {'id': 784, 'codigo_nota_fiscal': 'NF 171', 'c...        None
1  {'id': 787, 'codigo_nota_fiscal': 'NF 182', 'c...        None
2  {'id': 787, 'codigo_nota_fiscal': 'NF 182', 'c...        None
3  {'id': 787, 'codigo_nota_fiscal': 'NF 182', 'c...        None
4  {'id': 787, 'codigo_nota_fiscal': 'NF 182', 'c...        None

  dados_responsavel
0              None
1              None
2              None
3              None
4              None

[5 rows x 48 columns]

In [7]:
particpantes_url = f"{polotrial_url}/participantes"

logger.info("Iniciando coleta de participantes")

query_params = {
    "nested": "true",
}

try:

    response = requests.get(
        particpantes_url,
        headers=endpoint_headers,
        params=query_params,
        timeout=30
    )

    logger.info(f"Status rota participantes: {response.status_code}")

    response.raise_for_status()

    participantes = response.json()

    if not participantes:
        logger.warning("API retornou lista de participantes vazia")

    # tratamento do formato do JSON
    if isinstance(participantes, dict):
        participantes = [participantes]

    participantes_df = pd.DataFrame(participantes)

    logger.info(f"DataFrame participantes criado com {len(participantes_df)} registros")
    logger.info(f"Shape participantes_df: {participantes_df.shape}")
    logger.info(f"Colunas participantes_df: {participantes_df.columns.tolist()}")

    logger.info("Primeiras linhas do dataframe participantes:")
    logger.info(f"\n{participantes_df.head()}")

except Exception as e:

    logger.error(f"Erro ao consultar rota participantes: {e}")
    raise

2026-03-12 16:41:08,483 | INFO | Iniciando coleta de participantes
2026-03-12 16:41:13,054 | INFO | Status rota participantes: 200
2026-03-12 16:41:13,217 | INFO | DataFrame participantes criado com 2507 registros
2026-03-12 16:41:13,218 | INFO | Shape participantes_df: (2507, 37)
2026-03-12 16:41:13,218 | INFO | Colunas participantes_df: ['id', 'co_protocolo', 'id_participante', 'id_instituicao', 'nome', 'origem_indicacao', 'status_participante', 'iniciais', 'contatos', 'data_nascimento', 'observacoes', 'data_inclusao', 'data_randomizacao', 'numero_de_screening', 'numero_de_randomizacao', 'ressarcimento', 'co_braco', 'co_voluntario', 'limite_randomizacao', 'data_fim_tratamento', 'atualizar_agenda', 'anexo_tcle', 'data_assinatura_tcle', 'data_da_falha', 'ultima_visita', 'proxima_visita', 'apagar_visitas_pendentes', 'co_status_gn', 'co_participante', 'dados_protocolo', 'dados_status', 'dados_braco', 'dados_voluntario', 'ParticipantesVisita', 'ParticipanteUltimaVisita', 'dados_proxima_visita', 'dados_equipe_protocolo']
2026-03-12 16:41:13,219 | INFO | Primeiras linhas do dataframe participantes:
2026-03-12 16:41:13,239 | INFO |
   id  co_protocolo id_participante id_instituicao  \
0  54             4            1001        5684766
1  56             4            1002        5689356
2  57             4            1003        5695907
3  58             4            1004        5703918
4  59             4            1005        5710802

                            nome  origem_indicacao  status_participante  \
0         Antonino Marmor Gomide               NaN                  308
1       Maria Pereira dos Santos               NaN                  308
2  Maria Sebastiana Babosa Vitor               NaN                  310
3         Ronaldo Gomes da Silva               NaN                  308
4          Gilson Duarte Matioli               NaN                  308

  iniciais     contatos data_nascimento  ... co_status_gn co_participante  \
0    A.M.G  11999999999      1945-02-22  ...          308              54
1    M.P.S  11999999999      1963-12-31  ...          308              56
2    M.S.V  11999999999      1957-01-20  ...          310              57
3    R.G.S  11999999999      1965-01-05  ...          308              58
4    G.D.M  11999999999      1956-10-07  ...          308              59

                         dados_protocolo  \
0  {'id': 4, 'apelido_protocolo': 'BTK'}
1  {'id': 4, 'apelido_protocolo': 'BTK'}
2  {'id': 4, 'apelido_protocolo': 'BTK'}
3  {'id': 4, 'apelido_protocolo': 'BTK'}
4  {'id': 4, 'apelido_protocolo': 'BTK'}

                                      dados_status  \
0         {'id': 308, 'ds_descricao': 'Concluído'}
1         {'id': 308, 'ds_descricao': 'Concluído'}
2  {'id': 310, 'ds_descricao': 'Falha de seleção'}
3         {'id': 308, 'ds_descricao': 'Concluído'}
4         {'id': 308, 'ds_descricao': 'Concluído'}

                  dados_braco  \
0  {'id': 1, 'nome': 'Único'}
1  {'id': 1, 'nome': 'Único'}
2  {'id': 1, 'nome': 'Único'}
3  {'id': 1, 'nome': 'Único'}
4  {'id': 1, 'nome': 'Único'}

                                    dados_voluntario  \
0  {'id': 54, 'iniciais': 'A.M.G', 'ds_nome': 'An...
1  {'id': 55, 'iniciais': 'M.P.S', 'ds_nome': 'Ma...
2  {'id': 56, 'iniciais': 'M.S.V', 'ds_nome': 'Ma...
3  {'id': 57, 'iniciais': 'R.G.S', 'ds_nome': 'Ro...
4  {'id': 58, 'iniciais': 'G.D.M', 'ds_nome': 'Gi...

                                 ParticipantesVisita  \
0  [{'id': 639, 'co_participante': 54, 'co_visita...
1  [{'id': 640, 'co_participante': 56, 'co_visita...
2  [{'id': 641, 'co_participante': 57, 'co_visita...
3  [{'id': 642, 'co_participante': 58, 'co_visita...
4  [{'id': 643, 'co_participante': 59, 'co_visita...

                            ParticipanteUltimaVisita dados_proxima_visita  \
0  {'id': 54, 'co_voluntario': 54, 'ultima_visita...                 None
1  {'id': 56, 'co_voluntario': 55, 'ultima_visita...                 None
2  {'id': 57, 'co_voluntario': 56, 'ultima_visita...                 None
3  {'id': 58, 'co_voluntario': 57, 'ultima_visita...                 None
4  {'id': 59, 'co_voluntario': 58, 'ultima_visita...                 None

                              dados_equipe_protocolo
0  [{'id': 19, 'co_protocolo': 4, 'co_pessoa': 19...
1  [{'id': 19, 'co_protocolo': 4, 'co_pessoa': 19...
2  [{'id': 19, 'co_protocolo': 4, 'co_pessoa': 19...
3  [{'id': 19, 'co_protocolo': 4, 'co_pessoa': 19...
4  [{'id': 19, 'co_protocolo': 4, 'co_pessoa': 19...

[5 rows x 37 columns]

In [8]:
monitoria_url = f"{polotrial_url}/agenda"

logger.info("Iniciando coleta de dados de monitoria")

query_params = {
    "nested": "true",
}

try:

    response = requests.get(
        monitoria_url,
        headers=endpoint_headers,
        params=query_params,
        timeout=30
    )

    logger.info(f"Status rota agenda: {response.status_code}")

    response.raise_for_status()

    monitoria = response.json()

    if not monitoria:
        logger.warning("API retornou agenda de monitoria vazia")

    if isinstance(monitoria, dict):
        monitoria = [monitoria]

    monitoria_df = pd.DataFrame(monitoria)

    logger.info(f"DataFrame monitoria criado com {len(monitoria_df)} registros")
    logger.info(f"Shape monitoria_df: {monitoria_df.shape}")
    logger.info(f"Colunas monitoria_df: {monitoria_df.columns.tolist()}")

    logger.info("Primeiras linhas da agenda de monitoria:")
    logger.info(f"\n{monitoria_df.head()}")

except Exception as e:

    logger.error(f"Erro ao consultar rota agenda: {e}")
    raise

2026-03-12 16:41:13,250 | INFO | Iniciando coleta de dados de monitoria
2026-03-12 16:41:20,319 | INFO | Status rota agenda: 200
2026-03-12 16:41:20,812 | INFO | DataFrame monitoria criado com 17920 registros
2026-03-12 16:41:20,813 | INFO | Shape monitoria_df: (17920, 43)
2026-03-12 16:41:20,814 | INFO | Colunas monitoria_df: ['id', 'tipo_evento', 'titulo', 'ds_co_industria', 'ds_co_hc', 'co_participante', 'tipo', 'status_evento', 'data_estimada', 'data_estimada_fim', 'data_realizada', 'data_estimada_filter', 'data_realizada_filter', 'responsavel', 'responsavel_nome', 'local', 'local_text', 'cor_status', 'observacoes', 'co_objeto', 'co_protocolo', 'co_coordenador', 'co_centro', 'filter1', 'valor_previsto', 'data_preenchimento_crf', 'data_preenchimento_visita', 'visita_extra', 'data_agenda', 'color', 'title', 'co_visita_referencia', 'filtro_dias', 'co_externo', 'data_limite_min', 'data_limite_max', 'data_ideal', 'dados_tipo', 'dados_status', 'dados_protocolo', 'dados_participante', 'dados_responsavel', 'dados_local']
2026-03-12 16:41:20,815 | INFO | Primeiras linhas da agenda de monitoria:
2026-03-12 16:41:20,823 | INFO |
   id  tipo_evento             titulo ds_co_industria ds_co_hc  \
0   1            1         Centriguga
1   4            1        contrato V6
2   5            1  contrato_ Graviti
3   6            1  contrato_ Graviti
4   7            1     Vencimento GCP

  co_participante  tipo  status_evento             data_estimada  \
0                     4             20  2022-04-28T00:00:00.000Z
1                     6             20  2022-07-06T00:00:00.000Z
2                     6             20  2022-12-29T00:00:00.000Z
3                     6             20  2022-12-29T00:00:00.000Z
4                     7             20  2025-08-16T00:00:00.000Z

          data_estimada_fim  ... co_externo data_limite_min data_limite_max  \
0                       NaN  ...       None             NaN             NaN
1                       NaN  ...       None             NaN             NaN
2                       NaN  ...       None             NaN             NaN
3                       NaN  ...       None             NaN             NaN
4  2025-08-16T00:00:00.000Z  ...       None             NaN             NaN

   data_ideal                           dados_tipo  \
0         NaN      {'id': 4, 'tipo': 'Calibração'}
1         NaN        {'id': 6, 'tipo': 'Contrato'}
2         NaN        {'id': 6, 'tipo': 'Contrato'}
3         NaN        {'id': 6, 'tipo': 'Contrato'}
4         NaN  {'id': 7, 'tipo': 'Vencimento GCP'}

                                        dados_status  \
0  {'id': 20, 'ds_descricao': 'Realizada', 'cor_s...
1  {'id': 20, 'ds_descricao': 'Realizada', 'cor_s...
2  {'id': 20, 'ds_descricao': 'Realizada', 'cor_s...
3  {'id': 20, 'ds_descricao': 'Realizada', 'cor_s...
4  {'id': 20, 'ds_descricao': 'Realizada', 'cor_s...

                                     dados_protocolo dados_participante  \
0                                               None               None
1  {'id': 53, 'apelido_protocolo': 'Dipro', 'co_c...               None
2  {'id': 322, 'apelido_protocolo': 'Graviti', 'c...               None
3  {'id': 322, 'apelido_protocolo': 'Graviti', 'c...               None
4                                               None               None

                                   dados_responsavel  \
0                                               None
1                                               None
2                                               None
3                                               None
4  {'id': 239, 'ds_nome': 'Caroline Pinheiro Vian...

                              dados_local
0                                    None
1                                    None
2                                    None
3                                    None
4  {'id': 765, 'ds_descricao': 'Virtual'}

[5 rows x 43 columns]

*** Visualização e modelagem para extração de GCP (cadastros ativos)

In [9]:
pessoas_df.head(5)

,dados_ativo,id,ds_nome,co_tipo_gn,co_equipe_gn,co_formacao_maior_nivel_gn,dt_ultimo_certificado_gcp,registro_profissional,declaracao_confidencialidade,custo_mensal_estimado,...,status,dados_co_tipo_gn,dados_co_equipe_gn,dados_co_formacao_maior_nivel_gn,dados_status,dados_centro,dados_equipe_padrao_farmacia,dados_equipe_padrao_kits,dados_equipe_padrao,dados_pessoa_especialidade
0,{'descricao': 'Sim'},2978,NaN,562.0,None,NaN,NaN,NaN,None,None,...,NaN,"{'id': 562, 'ds_descricao': 'Equipe padrão (ad...",None,None,None,None,None,None,None,[]
1,{'descricao': 'Sim'},3545,NaN,562.0,None,NaN,NaN,NaN,None,None,...,NaN,"{'id': 562, 'ds_descricao': 'Equipe padrão (ad...",None,None,None,None,None,None,None,[]
2,{'descricao': 'Sim'},1332,,649.0,None,NaN,NaN,NaN,None,None,...,NaN,"{'id': 649, 'ds_descricao': 'Participante'}",None,None,None,None,None,None,None,[]
3,{'descricao': 'Sim'},3118,Alex Gonçalves Macedo,387.0,None,31.0,2023-09-06,74.334/SP,None,None,...,9404.0,"{'id': 387, 'ds_descricao': 'Pesquisador Princ...",None,"{'id': 31, 'ds_descricao': 'Mestrado'}","{'id': 9404, 'ds_descricao': 'Ativo'}","{'id': 4, 'descricao': 'Santa Casa de Santos'}",None,None,None,"[{'id': 150, 'co_pessoa': 3118, 'co_pessoa_esp..."
4,{'descricao': 'Sim'},1554,Alex Vladimir Dudzic,649.0,None,NaN,NaN,NaN,None,None,...,NaN,"{'id': 649, 'ds_descricao': 'Participante'}",None,None,None,None,None,None,None,[]

In [10]:
colunas = [
    'dados_centro',
    'dt_ultimo_certificado_gcp',
    'ds_nome',
    'dados_co_tipo_gn',
    'dados_status'
]

faltantes = [c for c in colunas if c not in pessoas_df.columns]
if faltantes:
    raise Exception(f"Colunas ausentes: {faltantes}")
gcp = pessoas_df[colunas].copy()

gcp.loc[:, 'dados_centro_id'] = gcp['dados_centro'].apply(lambda x: x['id'] if x is not None else None)
gcp.loc[:, 'dados_centro_descricao'] = gcp['dados_centro'].apply(lambda x: x['descricao'] if x is not None else None)
gcp.loc[:, 'tipo_gn'] = gcp['dados_co_tipo_gn'].apply(lambda x: x['ds_descricao'] if x is not None else None)
gcp.loc[:, 'status'] = gcp['dados_status'].apply(lambda x: x['ds_descricao'] if x is not None else None)

gcp_ativos = gcp.drop(['dados_centro', 'dados_centro_id', 'dados_co_tipo_gn', 'dados_status'], axis=1)
gcp_modelado = gcp_ativos[gcp_ativos['status'] == 'Ativo']

gcp_modelado.head(5)

,dt_ultimo_certificado_gcp,ds_nome,dados_centro_descricao,tipo_gn,status
3,2023-09-06,Alex Gonçalves Macedo,Santa Casa de Santos,Pesquisador Principal,Ativo
5,NaN,Augusto Ferreira José,Santa Casa de Santos,Subinvestigador,Ativo
6,NaN,Dr. Ricardo Moro,Clinica de Ortopedia Campo Largo S/S LTDA,Pesquisador Principal,Ativo
313,NaN,Adão Castelo Antônio,Hospital Municipal de Barueri,Pesquisador Principal,Ativo
385,2025-06-26,Alessandro Vengjer,Santa Casa de Santos,Pesquisador Principal,Ativo

In [11]:
venc_gcp = gcp_modelado[gcp_modelado['tipo_gn'] != 'Equipe padrão (adicionada automaticamente para todos os protocolos)']
venc_gcp["Cadastro de data"] = venc_gcp["dt_ultimo_certificado_gcp"].apply(
    lambda x: "Não há data cadastrada" if pd.isna(x) else "Data cadastrada"
)

venc_gcp.rename(columns={'dt_ultimo_certificado_gcp': 'Assinatura do GCP', 'ds_nome': 'Nome', 'dados_centro_descricao': 'Centro','tipo_gn': 'Função', 'status': 'Status do Cadastro'}, inplace=True)

nova_ordem = ['Centro', 'Nome', 'Função','Status do Cadastro', 'Assinatura do GCP', "Cadastro de data"]
venc_gcp = venc_gcp[nova_ordem]
venc_gcp = venc_gcp.sort_values(by="Centro")
venc_gcp

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
1124,A2Z Clinical Centro Avancado De Pesquisa Clini...,Dr. Fernando Henrique de Carvalho Gouvêa,Equipe Médica,Ativo,NaN,Não há data cadastrada
1296,Centro Médico Sinapse,Dr. Ricardo Moutte de Freitas,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1210,Centro Vila Olimpia,Dr. Leandro Tuzuki Cavalheiro,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1332,Centro de Oncologia do Panará,Dr. Thadeu Tiessi Suzuki,Pesquisador Principal,Ativo,2025-11-10,Data cadastrada
1122,Clin Kids,Dr. Fernando Bedoni,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
...,...,...,...,...,...,...
1583,NaN,Eduardo Ramacciotti,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1798,NaN,Francine Heiko,Subinvestigador,Ativo,NaN,Não há data cadastrada
1800,NaN,Francine Heiko Alves Perpétuo,Subinvestigador,Ativo,NaN,Não há data cadastrada
3170,NaN,Nathalia de Oliveira Westphalen,Subinvestigador,Ativo,NaN,Não há data cadastrada
3281,NaN,Paula Sant' Anna,Subinvestigador,Ativo,NaN,Não há data cadastrada

In [12]:
hmcg = ['Leforte HMCG','Leforte Morumbi','Hospital Municipal de Barueri', 'Leforte Liberdade', 'Clínica CardialMed','Clínica CardialMed']
filtro1 = venc_gcp['Centro'].isin(hmcg)
venc_gcp_hmcg = venc_gcp[filtro1]
venc_gcp_hmcg=venc_gcp_hmcg.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_hmcg

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
1166,Clínica CardialMed,Dr. Heron Rhydan Saad Rached,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1472,Clínica CardialMed,Dra. Maristela Gomes de Almeida,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
2042,Clínica CardialMed,Heron Rhydan Saad Rached,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
2130,Clínica CardialMed,Izabella Cordeiro Freire Saad Rached,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
313,Hospital Municipal de Barueri,Adão Castelo Antônio,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
...,...,...,...,...,...,...
1127,Leforte Morumbi,Dr. Fernando Reis Menezes,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1474,Leforte Morumbi,Dra. Mayara de Almeida Rodrigues da Costa,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1504,Leforte Morumbi,Dra. Samantha Rodrigues Camargo Neves,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1776,Leforte Morumbi,Fernando Reis Menezes,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
2926,Leforte Morumbi,Mayara de Almeida Rodrigues da Costa,Pesquisador Principal,Ativo,NaN,Não há data cadastrada

In [13]:
rocio = ['Maternidade e Cirurgia Nossa Senhora do Rocio SA']
filtro2 = venc_gcp['Centro'].isin(rocio)
venc_gcp_rocio = venc_gcp[filtro2]
venc_gcp_rocio=venc_gcp_rocio.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_rocio

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
533,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Andre Luiz Santos Cerneck,Subinvestigador,Ativo,2021-09-16,Data cadastrada
535,Maternidade e Cirurgia Nossa Senhora do Rocio SA,André Ricardo Fuck,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
683,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Brenno Giovanni Hernando Vidotti,Subinvestigador,Ativo,NaN,Não há data cadastrada
684,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Brenno Giovanni Hernando Vidotti,Subinvestigador,Ativo,NaN,Não há data cadastrada
763,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Carlos Alberto Kenji Nakashima,Subinvestigador,Ativo,NaN,Não há data cadastrada
824,Maternidade e Cirurgia Nossa Senhora do Rocio SA,César de Oliveira Lopes Dusilek,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
903,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dalton Luiz Rivabem Júnior,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
923,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Daniele Nogueira Rodrigues dos Santos,Subinvestigador,Ativo,NaN,Não há data cadastrada
931,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Danillo Taiguara Ramos Gomes da Silva,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1017,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Alvaro Viera Moura,Subinvestigador,Ativo,NaN,Não há data cadastrada
1023,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. André Ricardo Fuck,Pesquisador Principal,Ativo,2023-03-14,Data cadastrada
1050,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Carlos A. Kenji Nakashima,Subinvestigador,Ativo,NaN,Não há data cadastrada
1051,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Carlos Alberto Kenji Nakashima,Subinvestigador,Ativo,NaN,Não há data cadastrada
1064,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. César de Oliveira Lopes Dusilek,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1085,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Diego Carvalho Duarte Mari,Pesquisador Principal,Ativo,2022-09-06,Data cadastrada
1086,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Diego Roberto Rolim Vaciloto,Subinvestigador,Ativo,NaN,Não há data cadastrada
1120,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Felipe Fernandes Monteiro,Subinvestigador,Ativo,NaN,Não há data cadastrada
1121,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Felipe Fernandes Monteiro,Pesquisador Principal,Ativo,2020-08-21,Data cadastrada
1160,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Guilherme Vinicius de Andrade Barbosa,Equipe Médica,Ativo,2021-09-16,Data cadastrada
1185,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. João Guilherme de Toledo Justo,Subinvestigador,Ativo,NaN,Não há data cadastrada
1206,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Leandro Cardoso Canuto Vasconcelos,Subinvestigador,Ativo,NaN,Não há data cadastrada
1214,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Leonardo Ferreira Dias,Subinvestigador,Ativo,NaN,Não há data cadastrada
1297,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Ricardo Nascimento Riet,Subinvestigador,Ativo,2021-09-10,Data cadastrada
1301,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Ricardo Riet,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1308,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Roberto Tauchmann,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1357,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dra. Amanda Pizzato da Silveira,Subinvestigador,Ativo,2021-06-21,Data cadastrada
1398,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dra. Daniele Nogueira Santos,Subinvestigador,Ativo,2021-06-06,Data cadastrada
1440,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dra. Juliana Graziele Nogueira Rodrigues dos S...,Subinvestigador,Ativo,2021-09-16,Data cadastrada
1447,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dra. Lais Prigol Ruzzon,Subinvestigador,Ativo,NaN,Não há data cadastrada
1568,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Eduardo Hummelgen,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1720,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Fabiola Pedron Peres da Costa,Subinvestigador,Ativo,NaN,Não há data cadastrada
1719,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Fabiola Pedron Peres da Costa,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
2395,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Kengi Itinose,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
2570,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Lucas Roberto Rivabem Ferreira,Subinvestigador,Ativo,NaN,Não há data cadastrada
2655,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Maikele Ertel,Subinvestigador,Ativo,NaN,Não há data cadastrada
2688,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Marcelo Sávio Paiva Do Amaral Filho,Equipe Médica,Ativo,NaN,Não há data cadastrada
2689,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Marcelo Sávio Paiva do Amaral Filho,Subinvestigador,Ativo,NaN,Não há data cadastrada
3336,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Rafael Pasini Del Claro,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3419,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Ricardo Nascimento Riet,Subinvestigador,Ativo,NaN,Não há data cadastrada
3441,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Roberto Tauchmann,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3514,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Rui Portes da Silva Filho,Subinvestigador,Ativo,NaN,Não há data cadastrada

In [14]:
iir_coord = ['Hospital das Clínicas de Itajubá', 'Saint-Beauté Clinique', 'Hospital Salvalus','Consultório Lopes e Sartorelli', 'Clínica Berger', 
            'QualiVida Higienópolis','Endolap Saúde' ]
filtro3 = venc_gcp['Centro'].isin(iir_coord)
venc_gcp_iir_coord = venc_gcp[filtro3] 
venc_gcp_iir_coord=venc_gcp_iir_coord.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_iir_coord

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
1065,Clínica Berger,Dr. Charles Berger,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3175,Consultório Lopes e Sartorelli,Nathalia Westphalen,Equipe Médica,Ativo,NaN,Não há data cadastrada

In [15]:
envio_viviane = ['Otorhinus Clínica Médica', 'Unimed Brusque']
filtro4 = venc_gcp['Centro'].isin(envio_viviane)
venc_gcp_envio_viviane = venc_gcp[filtro4]
venc_gcp_envio_viviane=venc_gcp_envio_viviane.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_envio_viviane

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
1277,Otorhinus Clínica Médica,Dr. Rafael Leonardo Emerich Lentz Martins,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3333,Otorhinus Clínica Médica,Rafael Leonardo Emerich Lentz Martins,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1030,Unimed Brusque,Dr. Antonio Carlos de Mattos Roxo,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1077,Unimed Brusque,Dr. Daniel Rodrigo Klein,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1112,Unimed Brusque,Dr. Fabio Benedetti,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1126,Unimed Brusque,Dr. Fernando Kamimoto Eckmann Helene,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1113,Unimed Brusque,Dr. Fábio Benedetti Rodrigues,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1172,Unimed Brusque,Dr. Ismael Paulo Búrigo,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1204,Unimed Brusque,Dr. Laércio Cadore,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1230,Unimed Brusque,Dr. Luiz Fernando Silveira Parrela,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1250,Unimed Brusque,Dr. Marcus Vitor Oliveira,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1269,Unimed Brusque,Dr. Paulo Cesar de Campos Ferreira,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1311,Unimed Brusque,Dr. Rodrigo Kraft Rovere,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1325,Unimed Brusque,Dr. Sebastião Dutra de Morais Júnior,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1330,Unimed Brusque,Dr. Sílvio Soares Nogueira,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1341,Unimed Brusque,Dr. Victor Daniel Schiocchet Monarim,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1362,Unimed Brusque,Dra. Ana Kris da Silva Sommariva,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1369,Unimed Brusque,Dra. Angelica Cristina da Silva Nóbrega,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1370,Unimed Brusque,Dra. Angelica Cristina dos Santos Nóbrega,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1371,Unimed Brusque,Dra. Anita Silva Brunel Alves,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1375,Unimed Brusque,Dra. Barbara Fiorentin Giordani Gamba,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1396,Unimed Brusque,Dra. Daniela Salvador Alves,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1415,Unimed Brusque,Dra. Fernanda Arns de Castro,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1471,Unimed Brusque,Dra. Marina Passos Seixas,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1473,Unimed Brusque,Dra. Marta Amaro da Silveira Duval,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1506,Unimed Brusque,Dra. Sura Amélia Barbosa Félix Leão,Pesquisador Principal,Ativo,NaN,Não há data cadastrada

In [16]:
stacasa_santos = ['Santa Casa de Santos']
filtro5 = venc_gcp['Centro'].isin(stacasa_santos)
venc_gcp_stacasa_santos = venc_gcp[filtro5]
venc_gcp_stacasa_santos=venc_gcp_stacasa_santos.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_stacasa_santos

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
3,Santa Casa de Santos,Alex Gonçalves Macedo,Pesquisador Principal,Ativo,2023-09-06,Data cadastrada
5,Santa Casa de Santos,Augusto Ferreira José,Subinvestigador,Ativo,NaN,Não há data cadastrada
385,Santa Casa de Santos,Alessandro Vengjer,Pesquisador Principal,Ativo,2025-06-26,Data cadastrada
520,Santa Casa de Santos,André Galante Alencar Aranha,Pesquisador Principal,Ativo,2021-09-23,Data cadastrada
522,Santa Casa de Santos,André Gustavo Pereira Magalhães,Subinvestigador,Ativo,NaN,Não há data cadastrada
...,...,...,...,...,...,...
3439,Santa Casa de Santos,Roberto Higa Junior,Subinvestigador,Ativo,NaN,Não há data cadastrada
3529,Santa Casa de Santos,Samuel Brunini Petrarolha,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3528,Santa Casa de Santos,Samuel Brunini Petrarolha,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3826,Santa Casa de Santos,Vitor Hugo Straub,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3827,Santa Casa de Santos,Vitor Hugo Straub Canasiro,Pesquisador Principal,Ativo,NaN,Não há data cadastrada

In [17]:
capibaribe = ['Hospital do Capibaribe']
filtro6 = venc_gcp['Centro'].isin(capibaribe)
venc_gcp_capibaribe = venc_gcp[filtro6]
venc_gcp_capibaribe=venc_gcp_capibaribe.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_capibaribe

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
1180,Hospital do Capibaribe,Dr. Jayme José Gouveia Filho,Equipe Médica,Ativo,2024-09-23,Data cadastrada
1469,Hospital do Capibaribe,Dra. Mariane Teodoro Fernandes Rodrigues,Pesquisador Principal,Ativo,2024-06-14,Data cadastrada
2841,Hospital do Capibaribe,Mariane Teodoro Fernandes Rodrigues,Pesquisador Principal,Ativo,NaN,Não há data cadastrada

***Função para cálculo da data de vencimento de GCP.

In [ ]:
def verificar_vencimento_contratos(df_contratos, nome_centro, dias_para_vencimento=30):

    logger.info(f"Iniciando verificação de vencimento de GCP para {nome_centro}")

    if df_contratos.empty:
        logger.warning(f"{nome_centro}: dataframe de contratos está vazio")
        return df_contratos

    df_contratos = df_contratos.copy()

    df_contratos['Assinatura do GCP'] = pd.to_datetime(
        df_contratos['Assinatura do GCP'],
        errors='coerce'
    )

    hoje = datetime.today()
    limite_vencimento = hoje + timedelta(days=dias_para_vencimento)

    df_contratos['data_vencimento'] = (
        df_contratos['Assinatura do GCP'] + timedelta(days=2 * 365)
    )

    filtro_vencendo = (
        (df_contratos['data_vencimento'] > hoje) &
        (df_contratos['data_vencimento'] <= limite_vencimento)
    )

    filtro_sem_data = df_contratos['Assinatura do GCP'].isna()

    contratos_relevantes = df_contratos[filtro_vencendo | filtro_sem_data]

    logger.info(
        f"{nome_centro}: {len(df_contratos)} contratos analisados"
    )

    logger.info(
        f"{nome_centro}: {len(contratos_relevantes)} contratos com alerta"
    )

    if contratos_relevantes.empty:

        logger.info(
            f"{nome_centro}: nenhum contrato sem data de GCP ou vencendo "
            f"nos próximos {dias_para_vencimento} dias"
        )

    else:

        logger.warning(
            f"{nome_centro}: profissionais com GCP ausente ou vencendo "
            f"nos próximos {dias_para_vencimento} dias"
        )

        logger.info(
            f"\n{contratos_relevantes[['Centro', 'Nome', 'Função','Status do Cadastro', 'Assinatura do GCP', 'Cadastro de data']]}"
        )

    return contratos_relevantes

In [19]:
contratos_hmcg = verificar_vencimento_contratos(venc_gcp_hmcg, "HMCG", dias_para_vencimento=30)
contratos_rocio = verificar_vencimento_contratos(venc_gcp_rocio, "Rocío", dias_para_vencimento=30)
contratos_iir_coord = verificar_vencimento_contratos(venc_gcp_iir_coord, "IRR COORD", dias_para_vencimento=30)
contratos_vivi = verificar_vencimento_contratos(venc_gcp_envio_viviane, "Envio Viviane", dias_para_vencimento=30)
contratos_stacsantos = verificar_vencimento_contratos(venc_gcp_stacasa_santos, "Santa Casa de Santos", dias_para_vencimento=30)
contratos_capibaribe = verificar_vencimento_contratos(venc_gcp_capibaribe, "Capibaribe", dias_para_vencimento=30)

2026-03-12 16:41:21,166 | INFO | Iniciando verificação de vencimento de GCP para HMCG
2026-03-12 16:41:21,171 | INFO | HMCG: 87 contratos analisados
2026-03-12 16:41:21,171 | INFO | HMCG: 83 contratos com alerta
2026-03-12 16:41:21,171 | WARNING | HMCG: profissionais com GCP ausente ou vencendo nos próximos 30 dias
2026-03-12 16:41:21,180 | INFO |
                             Centro  \
1166             Clínica CardialMed
1472             Clínica CardialMed
2042             Clínica CardialMed
2130             Clínica CardialMed
313   Hospital Municipal de Barueri
...                             ...
1127                Leforte Morumbi
1474                Leforte Morumbi
1504                Leforte Morumbi
1776                Leforte Morumbi
2926                Leforte Morumbi

                                           Nome                 Função  \
1166               Dr. Heron Rhydan Saad Rached  Pesquisador Principal
1472            Dra. Maristela Gomes de Almeida  Pesquisador Principal
2042                   Heron Rhydan Saad Rached  Pesquisador Principal
2130       Izabella Cordeiro Freire Saad Rached  Pesquisador Principal
313                        Adão Castelo Antônio  Pesquisador Principal
...                                         ...                    ...
1127                  Dr. Fernando Reis Menezes  Pesquisador Principal
1474  Dra. Mayara de Almeida Rodrigues da Costa  Pesquisador Principal
1504      Dra. Samantha Rodrigues Camargo Neves  Pesquisador Principal
1776                      Fernando Reis Menezes  Pesquisador Principal
2926       Mayara de Almeida Rodrigues da Costa  Pesquisador Principal

     Status do Cadastro Assinatura do GCP        Cadastro de data
1166              Ativo               NaT  Não há data cadastrada
1472              Ativo               NaT  Não há data cadastrada
2042              Ativo               NaT  Não há data cadastrada
2130              Ativo               NaT  Não há data cadastrada
313               Ativo               NaT  Não há data cadastrada
...                 ...               ...                     ...
1127              Ativo               NaT  Não há data cadastrada
1474              Ativo               NaT  Não há data cadastrada
1504              Ativo               NaT  Não há data cadastrada
1776              Ativo               NaT  Não há data cadastrada
2926              Ativo               NaT  Não há data cadastrada

[83 rows x 6 columns]
2026-03-12 16:41:21,181 | INFO | Iniciando verificação de vencimento de GCP para Rocío
2026-03-12 16:41:21,183 | INFO | Rocío: 41 contratos analisados
2026-03-12 16:41:21,183 | INFO | Rocío: 32 contratos com alerta
2026-03-12 16:41:21,184 | WARNING | Rocío: profissionais com GCP ausente ou vencendo nos próximos 30 dias
2026-03-12 16:41:21,186 | INFO |
                                                Centro  \
535   Maternidade e Cirurgia Nossa Senhora do Rocio SA
683   Maternidade e Cirurgia Nossa Senhora do Rocio SA
684   Maternidade e Cirurgia Nossa Senhora do Rocio SA
763   Maternidade e Cirurgia Nossa Senhora do Rocio SA
824   Maternidade e Cirurgia Nossa Senhora do Rocio SA
903   Maternidade e Cirurgia Nossa Senhora do Rocio SA
923   Maternidade e Cirurgia Nossa Senhora do Rocio SA
931   Maternidade e Cirurgia Nossa Senhora do Rocio SA
1017  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1050  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1051  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1064  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1086  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1120  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1185  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1206  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1214  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1301  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1308  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1447  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1568  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1720  Maternidade e Cirurgia Nossa Senhora do Rocio SA
1719  Maternidade e Cirurgia Nossa Senhora do Rocio SA
2395  Maternidade e Cirurgia Nossa Senhora do Rocio SA
2570  Maternidade e Cirurgia Nossa Senhora do Rocio SA
2655  Maternidade e Cirurgia Nossa Senhora do Rocio SA
2688  Maternidade e Cirurgia Nossa Senhora do Rocio SA
2689  Maternidade e Cirurgia Nossa Senhora do Rocio SA
3336  Maternidade e Cirurgia Nossa Senhora do Rocio SA
3419  Maternidade e Cirurgia Nossa Senhora do Rocio SA
3441  Maternidade e Cirurgia Nossa Senhora do Rocio SA
3514  Maternidade e Cirurgia Nossa Senhora do Rocio SA

                                        Nome                 Função  \
535                       André Ricardo Fuck  Pesquisador Principal
683         Brenno Giovanni Hernando Vidotti        Subinvestigador
684         Brenno Giovanni Hernando Vidotti        Subinvestigador
763           Carlos Alberto Kenji Nakashima        Subinvestigador
824          César de Oliveira Lopes Dusilek  Pesquisador Principal
903               Dalton Luiz Rivabem Júnior  Pesquisador Principal
923    Daniele Nogueira Rodrigues dos Santos        Subinvestigador
931    Danillo Taiguara Ramos Gomes da Silva  Pesquisador Principal
1017                  Dr. Alvaro Viera Moura        Subinvestigador
1050           Dr. Carlos A. Kenji Nakashima        Subinvestigador
1051      Dr. Carlos Alberto Kenji Nakashima        Subinvestigador
1064     Dr. César de Oliveira Lopes Dusilek  Pesquisador Principal
1086        Dr. Diego Roberto Rolim Vaciloto        Subinvestigador
1120           Dr. Felipe Fernandes Monteiro        Subinvestigador
1185      Dr. João Guilherme de Toledo Justo        Subinvestigador
1206  Dr. Leandro Cardoso Canuto Vasconcelos        Subinvestigador
1214              Dr. Leonardo Ferreira Dias        Subinvestigador
1301                        Dr. Ricardo Riet  Pesquisador Principal
1308                   Dr. Roberto Tauchmann  Pesquisador Principal
1447                 Dra. Lais Prigol Ruzzon        Subinvestigador
1568                       Eduardo Hummelgen  Pesquisador Principal
1720           Fabiola Pedron Peres da Costa        Subinvestigador
1719           Fabiola Pedron Peres da Costa  Pesquisador Principal
2395                           Kengi Itinose  Pesquisador Principal
2570          Lucas Roberto Rivabem Ferreira        Subinvestigador
2655                           Maikele Ertel        Subinvestigador
2688     Marcelo Sávio Paiva Do Amaral Filho          Equipe Médica
2689     Marcelo Sávio Paiva do Amaral Filho        Subinvestigador
3336                 Rafael Pasini Del Claro  Pesquisador Principal
3419                 Ricardo Nascimento Riet        Subinvestigador
3441                       Roberto Tauchmann  Pesquisador Principal
3514               Rui Portes da Silva Filho        Subinvestigador

     Status do Cadastro Assinatura do GCP        Cadastro de data
535               Ativo               NaT  Não há data cadastrada
683               Ativo               NaT  Não há data cadastrada
684               Ativo               NaT  Não há data cadastrada
763               Ativo               NaT  Não há data cadastrada
824               Ativo               NaT  Não há data cadastrada
903               Ativo               NaT  Não há data cadastrada
923               Ativo               NaT  Não há data cadastrada
931               Ativo               NaT  Não há data cadastrada
1017              Ativo               NaT  Não há data cadastrada
1050              Ativo               NaT  Não há data cadastrada
1051              Ativo               NaT  Não há data cadastrada
1064              Ativo               NaT  Não há data cadastrada
1086              Ativo               NaT  Não há data cadastrada
1120              Ativo               NaT  Não há data cadastrada
1185              Ativo               NaT  Não há data cadastrada
1206              Ativo               NaT  Não há data cadastrada
1214              Ativo               NaT  Não há data cadastrada
1301              Ativo               NaT  Não há data cadastrada
1308              Ativo               NaT  Não há data cadastrada
1447              Ativo               NaT  Não há data cadastrada
1568              Ativo               NaT  Não há data cadastrada
1720              Ativo               NaT  Não há data cadastrada
1719              Ativo               NaT  Não há data cadastrada
2395              Ativo               NaT  Não há data cadastrada
2570              Ativo               NaT  Não há data cadastrada
2655              Ativo               NaT  Não há data cadastrada
2688              Ativo               NaT  Não há data cadastrada
2689              Ativo               NaT  Não há data cadastrada
3336              Ativo               NaT  Não há data cadastrada
3419              Ativo               NaT  Não há data cadastrada
3441              Ativo               NaT  Não há data cadastrada
3514              Ativo               NaT  Não há data cadastrada
2026-03-12 16:41:21,187 | INFO | Iniciando verificação de vencimento de GCP para IRR COORD
2026-03-12 16:41:21,188 | INFO | IRR COORD: 2 contratos analisados
2026-03-12 16:41:21,189 | INFO | IRR COORD: 2 contratos com alerta
2026-03-12 16:41:21,189 | WARNING | IRR COORD: profissionais com GCP ausente ou vencendo nos próximos 30 dias
2026-03-12 16:41:21,191 | INFO |
                              Centro                 Nome  \
1065                  Clínica Berger   Dr. Charles Berger
3175  Consultório Lopes e Sartorelli  Nathalia Westphalen

                     Função Status do Cadastro Assinatura do GCP  \
1065  Pesquisador Principal              Ativo               NaT
3175          Equipe Médica              Ativo               NaT

            Cadastro de data
1065  Não há data cadastrada
3175  Não há data cadastrada
2026-03-12 16:41:21,192 | INFO | Iniciando verificação de vencimento de GCP para Envio Viviane
2026-03-12 16:41:21,193 | INFO | Envio Viviane: 26 contratos analisados
2026-03-12 16:41:21,194 | INFO | Envio Viviane: 26 contratos com alerta
2026-03-12 16:41:21,195 | WARNING | Envio Viviane: profissionais com GCP ausente ou vencendo nos próximos 30 dias
2026-03-12 16:41:21,198 | INFO |
                        Centro                                       Nome  \
1277  Otorhinus Clínica Médica  Dr. Rafael Leonardo Emerich Lentz Martins
3333  Otorhinus Clínica Médica      Rafael Leonardo Emerich Lentz Martins
1030            Unimed Brusque          Dr. Antonio Carlos de Mattos Roxo
1077            Unimed Brusque                   Dr. Daniel Rodrigo Klein
1112            Unimed Brusque                        Dr. Fabio Benedetti
1126            Unimed Brusque       Dr. Fernando Kamimoto Eckmann Helene
1113            Unimed Brusque              Dr. Fábio Benedetti Rodrigues
1172            Unimed Brusque                    Dr. Ismael Paulo Búrigo
1204            Unimed Brusque                         Dr. Laércio Cadore
1230            Unimed Brusque         Dr. Luiz Fernando Silveira Parrela
1250            Unimed Brusque                  Dr. Marcus Vitor Oliveira
1269            Unimed Brusque         Dr. Paulo Cesar de Campos Ferreira
1311            Unimed Brusque                   Dr. Rodrigo Kraft Rovere
1325            Unimed Brusque       Dr. Sebastião Dutra de Morais Júnior
1330            Unimed Brusque                 Dr. Sílvio Soares Nogueira
1341            Unimed Brusque       Dr. Victor Daniel Schiocchet Monarim
1362            Unimed Brusque           Dra. Ana Kris da Silva Sommariva
1369            Unimed Brusque    Dra. Angelica Cristina da Silva Nóbrega
1370            Unimed Brusque  Dra. Angelica Cristina dos Santos Nóbrega
1371            Unimed Brusque              Dra. Anita Silva Brunel Alves
1375            Unimed Brusque      Dra. Barbara Fiorentin Giordani Gamba
1396            Unimed Brusque                Dra. Daniela Salvador Alves
1415            Unimed Brusque               Dra. Fernanda Arns de Castro
1471            Unimed Brusque                  Dra. Marina Passos Seixas
1473            Unimed Brusque         Dra. Marta Amaro da Silveira Duval
1506            Unimed Brusque        Dra. Sura Amélia Barbosa Félix Leão

                     Função Status do Cadastro Assinatura do GCP  \
1277  Pesquisador Principal              Ativo               NaT
3333  Pesquisador Principal              Ativo               NaT
1030  Pesquisador Principal              Ativo               NaT
1077  Pesquisador Principal              Ativo               NaT
1112  Pesquisador Principal              Ativo               NaT
1126  Pesquisador Principal              Ativo               NaT
1113  Pesquisador Principal              Ativo               NaT
1172  Pesquisador Principal              Ativo               NaT
1204  Pesquisador Principal              Ativo               NaT
1230  Pesquisador Principal              Ativo               NaT
1250  Pesquisador Principal              Ativo               NaT
1269  Pesquisador Principal              Ativo               NaT
1311  Pesquisador Principal              Ativo               NaT
1325  Pesquisador Principal              Ativo               NaT
1330  Pesquisador Principal              Ativo               NaT
1341  Pesquisador Principal              Ativo               NaT
1362  Pesquisador Principal              Ativo               NaT
1369  Pesquisador Principal              Ativo               NaT
1370  Pesquisador Principal              Ativo               NaT
1371  Pesquisador Principal              Ativo               NaT
1375  Pesquisador Principal              Ativo               NaT
1396  Pesquisador Principal              Ativo               NaT
1415  Pesquisador Principal              Ativo               NaT
1471  Pesquisador Principal              Ativo               NaT
1473  Pesquisador Principal              Ativo               NaT
1506  Pesquisador Principal              Ativo               NaT

            Cadastro de data
1277  Não há data cadastrada
3333  Não há data cadastrada
1030  Não há data cadastrada
1077  Não há data cadastrada
1112  Não há data cadastrada
1126  Não há data cadastrada
1113  Não há data cadastrada
1172  Não há data cadastrada
1204  Não há data cadastrada
1230  Não há data cadastrada
1250  Não há data cadastrada
1269  Não há data cadastrada
1311  Não há data cadastrada
1325  Não há data cadastrada
1330  Não há data cadastrada
1341  Não há data cadastrada
1362  Não há data cadastrada
1369  Não há data cadastrada
1370  Não há data cadastrada
1371  Não há data cadastrada
1375  Não há data cadastrada
1396  Não há data cadastrada
1415  Não há data cadastrada
1471  Não há data cadastrada
1473  Não há data cadastrada
1506  Não há data cadastrada
2026-03-12 16:41:21,199 | INFO | Iniciando verificação de vencimento de GCP para Santa Casa de Santos
2026-03-12 16:41:21,203 | INFO | Santa Casa de Santos: 114 contratos analisados
2026-03-12 16:41:21,204 | INFO | Santa Casa de Santos: 58 contratos com alerta
2026-03-12 16:41:21,204 | WARNING | Santa Casa de Santos: profissionais com GCP ausente ou vencendo nos próximos 30 dias
2026-03-12 16:41:21,210 | INFO |
                    Centro                                        Nome  \
5     Santa Casa de Santos                       Augusto Ferreira José
522   Santa Casa de Santos             André Gustavo Pereira Magalhães
523   Santa Casa de Santos             André Gustavo Pereira Magalhães
693   Santa Casa de Santos                     Bruna Giacomelli Moraes
656   Santa Casa de Santos                              Bárbara Maciel
910   Santa Casa de Santos                  Daniel de Carvalho Lustoza
924   Santa Casa de Santos                             Daniella Brasil
1014  Santa Casa de Santos    Dr. Alfredo Fernando Vecchiatti Pommella
1015  Santa Casa de Santos                  Dr. Altamiro Nostre Junior
1021  Santa Casa de Santos         Dr. André Gustavo Pereira Magalhães
1045  Santa Casa de Santos                   Dr. Bruno Oliveira Santos
1061  Santa Casa de Santos                    Dr. Carlos Vinetou Ayres
1071  Santa Casa de Santos                       Dr. Constantino Kader
1075  Santa Casa de Santos            Dr. Daniel Falconeres de Almeida
1079  Santa Casa de Santos                   Dr. Daniel Shammass Morel
1114  Santa Casa de Santos                      Dr. Fabio Crescentini
1170  Santa Casa de Santos                       Dr. Igor Marijuschkin
1182  Santa Casa de Santos                    Dr. Jefferson dos Santos
1201  Santa Casa de Santos       Dr. Kader Chafic Mancilha Daghastanli
1212  Santa Casa de Santos                   Dr. Leonardo Correa Silva
1213  Santa Casa de Santos  Dr. Leonardo Elamos de Rezende Vasconcelos
1220  Santa Casa de Santos                       Dr. Lucas Miotto José
1256  Santa Casa de Santos                 Dr. Matheus Moro Rabesquine
1306  Santa Casa de Santos                     Dr. Roberto Higa Junior
1310  Santa Casa de Santos               Dr. Rodrigo de Rosso e Grimas
1314  Santa Casa de Santos                        Dr. Rogério Nakasone
1328  Santa Casa de Santos                 Dr. Sérgio Feijoo Rodriguez
1334  Santa Casa de Santos               Dr. Thiago Ribeiro dos Santos
1380  Santa Casa de Santos       Dra. Bruna Giancomelli Moraes Carraro
1373  Santa Casa de Santos         Dra. Bárbara Andrade.Barbosa Maciel
1384  Santa Casa de Santos                   Dra. Carla Petreca Muzeti
1386  Santa Casa de Santos                Dra. Carolina Yamaguti Chaud
1401  Santa Casa de Santos                   Dra. Darlene Silva Polito
1404  Santa Casa de Santos                        Dra. Elaine Mancilha
1417  Santa Casa de Santos                 Dra. Fernanda Lovato de Sá
1423  Santa Casa de Santos           Dra. Gelvana Flávio Barreto Reis
1425  Santa Casa de Santos             Dra. Gleicy Luz Reinoso Pereira
1477  Santa Casa de Santos   Dra. Mirlene Cecilia Soares Pinho Cernach
1505  Santa Casa de Santos  Dra. Stephannie Fabiane Borges de Oliveira
1600  Santa Casa de Santos                             Elaine Mancilha
1604  Santa Casa de Santos                      Eliana Araújo da Silva
1702  Santa Casa de Santos                           Fabio Crescentini
1701  Santa Casa de Santos                           Fabio Crescentini
1733  Santa Casa de Santos                            Felipe Cervantes
2792  Santa Casa de Santos                Maria Heloiza Torres Ventura
2802  Santa Casa de Santos                            Maria Ligia Lyra
2803  Santa Casa de Santos                    Maria Ligia Lyra Pereira
2804  Santa Casa de Santos                    Maria Ligia Lyra Pereira
2918  Santa Casa de Santos                             Mauricio Sgarbi
3213  Santa Casa de Santos                             Nilson Gamberro
3384  Santa Casa de Santos                  Renan Francisco de Almeida
3435  Santa Casa de Santos                              Roberto Feolla
3438  Santa Casa de Santos                         Roberto Higa Junior
3439  Santa Casa de Santos                         Roberto Higa Junior
3529  Santa Casa de Santos                   Samuel Brunini Petrarolha
3528  Santa Casa de Santos                   Samuel Brunini Petrarolha
3826  Santa Casa de Santos                           Vitor Hugo Straub
3827  Santa Casa de Santos                  Vitor Hugo Straub Canasiro

                     Função Status do Cadastro Assinatura do GCP  \
5           Subinvestigador              Ativo               NaT
522         Subinvestigador              Ativo               NaT
523   Pesquisador Principal              Ativo               NaT
693         Subinvestigador              Ativo               NaT
656           Equipe Médica              Ativo               NaT
910   Pesquisador Principal              Ativo               NaT
924         Subinvestigador              Ativo               NaT

***Função para envio dos emails de GCP

In [20]:
css_hover = """
<style>
/* Reset básico */
table {
    border-collapse: collapse;
    width: 100%;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 13px;
}

/* Cabeçalho */
th {
    background-color: #007bff;
    color: #ffffff;
    border: 1px solid #d0d0d0;
    padding: 8px;
    text-align: left;
    font-weight: bold;
}

/* Células */
td {
    border: 1px solid #d0d0d0;
    padding: 8px;
    text-align: left;
    vertical-align: middle;
    color: #000000;
}

/* Linhas alternadas (mais compatível que hover) */
tr:nth-child(even) {
    background-color: #f8f9fa;
}

/* Hover (funciona em Gmail/Web, ignorado no Outlook) */
tr:hover {
    background-color: #fff3cd;
}

/* Responsividade simples */
@media screen and (max-width: 600px) {
    table {
        font-size: 12px;
    }
}
</style>
"""

Variáveis de envio de email

In [ ]:
smtp_server   = os.getenv("EMAIL_SERVER")
email_port    = int(os.getenv("EMAIL_PORT", "587"))
email_usuario = os.getenv("EMAIL_USERNAME")
email_senha   = os.getenv("EMAIL_PASSWORD")

# Destinatários GCP – variáveis individuais (strings simples)
enviar_para          = os.getenv("ENVIAR_PARA", "")
destinatario_hmcg    = os.getenv("DESTINATARIO_HMCG", "")
destinatario_rocio   = os.getenv("DESTINATARIO_ROCIO", "")
destinatario_scs     = os.getenv("DESTINATARIO_SCS", "")
destinatario_iir     = os.getenv("DESTINATARIO_IIR", "")
destinatario_vivi    = os.getenv("DESTINATARIO_VIVIANE", "")
destinatario_capibaribe = os.getenv("DESTINATARIO_CAPIBARIBE", "")

# Destinatário monitoria
envio_para = os.getenv("ENVIO_PARA", "")

def _parse_destinatarios(valor):
    """Converte string 'a@b.com,c@d.com' em lista de emails válidos."""
    email_regex = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    if not valor:
        return []
    emails = [e.strip() for e in valor.split(",") if e.strip()]
    validos = [e for e in emails if re.match(email_regex, e)]
    invalidos = set(emails) - set(validos)
    if invalidos:
        logger.warning(f"Emails ignorados por formato inválido: {invalidos}")
    return validos

In [ ]:
def enviar_email(destinatarios, df_tratado, nome_grupo):

    logger.info(f"Iniciando envio de email para grupo: {nome_grupo}")

    if df_tratado is None or df_tratado.empty:
        logger.info(f"{nome_grupo}: não há contratos para envio de email")
        return

    try:
        logger.info(f"{nome_grupo}: {len(df_tratado)} registros serão enviados no email")

        # garante lista e valida endereços
        if isinstance(destinatarios, str):
            destinatarios = _parse_destinatarios(destinatarios)
        else:
            destinatarios = [d for d in destinatarios if d]

        if not destinatarios:
            logger.warning(f"{nome_grupo}: nenhum destinatário válido. Email não enviado.")
            return

        logger.info(f"{nome_grupo}: destinatários -> {destinatarios}")

        colunas = [
            'Centro',
            'Nome',
            'Função',
            'Status do Cadastro',
            'Assinatura do GCP',
            'Cadastro de data'
        ]

        tabela_html = df_tratado[colunas].to_html(
            index=False,
            escape=False,
            border=0,
            justify="left",
            classes="table"
        )

        logger.info(f"{nome_grupo}: tabela HTML gerada")

        msg = MIMEMultipart("alternative")
        msg["From"]    = email_usuario
        msg["To"]      = email_usuario
        msg["Bcc"]     = ", ".join(destinatarios)
        msg["Subject"] = f"[{nome_grupo}] GCP sem data registrada ou com vencimento próximo"

        body = f"""
        <html>
            <head>{css_hover}</head>
            <body>
                <h2>Vencimento de GCP - {nome_grupo}</h2>
                <p>Bom dia,</p>
                <p>
                    Segue abaixo relação de GCPs que não possuem data registrada
                    no sistema ou que apresentam vencimento próximo:
                </p>
                {tabela_html}
                <br>
                <p>
                    Este e-mail é gerado automaticamente a partir de informações
                    inseridas na <strong>Polo Trial</strong>.
                </p>
                <p>
                    Qualquer dúvida, por favor, contate o
                    <strong><u>time BI - SVRI</u></strong>.
                </p>
            </body>
        </html>
        """

        msg.attach(MIMEText(body, "html"))

        logger.info(f"{nome_grupo}: conectando ao servidor SMTP {smtp_server}:{email_port}")

        with smtplib.SMTP(smtp_server, email_port) as server:
            server.starttls()
            logger.info(f"{nome_grupo}: TLS iniciado")
            server.login(email_usuario, email_senha)
            logger.info(f"{nome_grupo}: login SMTP realizado")
            server.send_message(msg)
            logger.info(f"{nome_grupo}: email enviado com sucesso")

    except Exception as e:
        logger.error(
            f"{nome_grupo}: erro ao enviar email -> {str(e)}",
            exc_info=True
        )

In [23]:
enviar_email([destinatario_hmcg], contratos_hmcg, "HMCG")
enviar_email([destinatario_rocio], contratos_rocio, "Rocio")
enviar_email([destinatario_iir], contratos_iir_coord, "IIR")
enviar_email([destinatario_scs], contratos_stacsantos, "Sta. Santos")
enviar_email([destinatario_vivi], contratos_vivi, "Viviane")
enviar_email([destinatario_capibaribe], contratos_capibaribe, "Capibaribe")

2026-03-12 16:41:21,283 | INFO | Iniciando envio de email para grupo: HMCG
2026-03-12 16:41:21,284 | INFO | HMCG: 83 registros serão enviados no email
2026-03-12 16:41:21,285 | INFO | HMCG: destinatários BCC -> ['sitehmcg@svriglobal.com']
2026-03-12 16:41:21,296 | INFO | HMCG: tabela HTML gerada
2026-03-12 16:41:21,300 | INFO | HMCG: corpo do email criado
2026-03-12 16:41:21,300 | INFO | HMCG: conectando ao servidor SMTP
2026-03-12 16:41:21,351 | INFO | HMCG: TLS iniciado
2026-03-12 16:41:21,464 | INFO | HMCG: login SMTP realizado
2026-03-12 16:41:22,047 | INFO | HMCG: email enviado com sucesso
2026-03-12 16:41:22,064 | INFO | Iniciando envio de email para grupo: Rocio
2026-03-12 16:41:22,064 | INFO | Rocio: 32 registros serão enviados no email
2026-03-12 16:41:22,064 | INFO | Rocio: destinatários BCC -> ['siterocio@svriglobal.com']
2026-03-12 16:41:22,064 | INFO | Rocio: tabela HTML gerada
2026-03-12 16:41:22,064 | INFO | Rocio: corpo do email criado
2026-03-12 16:41:22,064 | INFO | Rocio: conectando ao servidor SMTP
2026-03-12 16:41:22,147 | INFO | Rocio: TLS iniciado
2026-03-12 16:41:22,685 | INFO | Rocio: login SMTP realizado
2026-03-12 16:41:23,303 | INFO | Rocio: email enviado com sucesso
2026-03-12 16:41:23,313 | INFO | Iniciando envio de email para grupo: IIR
2026-03-12 16:41:23,314 | INFO | IIR: 2 registros serão enviados no email
2026-03-12 16:41:23,314 | INFO | IIR: destinatários BCC -> ['iir@svriglobal.com']
2026-03-12 16:41:23,318 | INFO | IIR: tabela HTML gerada
2026-03-12 16:41:23,319 | INFO | IIR: corpo do email criado
2026-03-12 16:41:23,321 | INFO | IIR: conectando ao servidor SMTP
2026-03-12 16:41:23,353 | INFO | IIR: TLS iniciado
2026-03-12 16:41:23,591 | INFO | IIR: login SMTP realizado
2026-03-12 16:41:23,864 | INFO | IIR: email enviado com sucesso
2026-03-12 16:41:23,870 | INFO | Iniciando envio de email para grupo: Sta. Santos
2026-03-12 16:41:23,870 | INFO | Sta. Santos: 58 registros serão enviados no email
2026-03-12 16:41:23,871 | INFO | Sta. Santos: destinatários BCC -> ['sitescsantos@svriglobal.com']
2026-03-12 16:41:23,877 | INFO | Sta. Santos: tabela HTML gerada
2026-03-12 16:41:23,879 | INFO | Sta. Santos: corpo do email criado
2026-03-12 16:41:23,879 | INFO | Sta. Santos: conectando ao servidor SMTP
2026-03-12 16:41:23,919 | INFO | Sta. Santos: TLS iniciado
2026-03-12 16:41:24,032 | INFO | Sta. Santos: login SMTP realizado
2026-03-12 16:41:24,437 | INFO | Sta. Santos: email enviado com sucesso
2026-03-12 16:41:24,443 | INFO | Iniciando envio de email para grupo: Viviane
2026-03-12 16:41:24,445 | INFO | Viviane: 26 registros serão enviados no email
2026-03-12 16:41:24,446 | INFO | Viviane: destinatários BCC -> ['viviane.santana@svriglobal.com, daniele.komar@svriglobal.com']
2026-03-12 16:41:24,452 | INFO | Viviane: tabela HTML gerada
2026-03-12 16:41:24,453 | INFO | Viviane: corpo do email criado
2026-03-12 16:41:24,454 | INFO | Viviane: conectando ao servidor SMTP
2026-03-12 16:41:24,517 | INFO | Viviane: TLS iniciado
2026-03-12 16:41:24,716 | INFO | Viviane: login SMTP realizado
2026-03-12 16:41:25,207 | INFO | Viviane: email enviado com sucesso
2026-03-12 16:41:25,212 | INFO | Iniciando envio de email para grupo: Capibaribe
2026-03-12 16:41:25,213 | INFO | Capibaribe: 1 registros serão enviados no email
2026-03-12 16:41:25,213 | INFO | Capibaribe: destinatários BCC -> ['sitecapibaribe@svriglobal.com']
2026-03-12 16:41:25,213 | INFO | Capibaribe: tabela HTML gerada
2026-03-12 16:41:25,217 | INFO | Capibaribe: corpo do email criado
2026-03-12 16:41:25,217 | INFO | Capibaribe: conectando ao servidor SMTP
2026-03-12 16:41:25,253 | INFO | Capibaribe: TLS iniciado
2026-03-12 16:41:25,583 | INFO | Capibaribe: login SMTP realizado
2026-03-12 16:41:26,066 | INFO | Capibaribe: email enviado com sucesso

***Modelagem para envio de Visitas de Seguimento

In [24]:
protocolo = pd.DataFrame(protocolos_dataframe)
protocolo.head(5)

,id,titulo_protocolo,cor_agenda,numero_protocolo,apelido_protocolo,coordenador,pi,pesquisador_backup,co_pessoa_regulatorio,data_cadastro,...,dados_medicamento_do_estudo,dados_pendencias_regulatorio,dados_status_feasibility,dados_status_contrato,dados_status_orcamento,dados_status_regulatorio,dados_status_recrutamento,dados_status_financeiro,dados_assistente_de_pesquisa,dados_dificuldade_recrutamento
0,784,"Um estudo randomizado, duplo-cego, controlado ...",#000000,LX4211.1-314-HCM,SONATA-HCM,2829.0,271,NaN,2631.0,2023-07-17T10:14:16.000Z,...,None,"{'id': 40, 'ds_descricao': 'Sim'}","{'id': 824, 'ds_descricao': 'Respondido'}","{'id': 9, 'ds_descricao': 'Em negociação com o...",None,"{'id': 914, 'ds_descricao': 'Aprovado'}",None,None,None,"{'id': 9292, 'ds_descricao': 'Moderado'}"
1,1256,"Estudo VISIONAIRE (Vitamin K AntagonISt, Facto...",#000000,,VISIONAIRE,2829.0,3050,NaN,2631.0,2023-11-30T09:28:12.000Z,...,None,"{'id': 40, 'ds_descricao': 'Sim'}","{'id': 824, 'ds_descricao': 'Respondido'}","{'id': 908, 'ds_descricao': 'Assinado'}","{'id': 877, 'ds_descricao': 'Aprovado'}","{'id': 918, 'ds_descricao': 'Em análise do CEP'}",None,None,None,None
2,1661,"Um ensaio randomizado, controlado por placebo,...",#9a514c,BIOTEST-996,EsSCAPE-996,239.0,250,NaN,2807.0,2024-06-07T14:43:21.000Z,...,None,"{'id': 40, 'ds_descricao': 'Sim'}","{'id': 824, 'ds_descricao': 'Respondido'}",None,None,"{'id': 914, 'ds_descricao': 'Aprovado'}","{'id': 936, 'ds_descricao': 'Recrutamento aber...",None,None,"{'id': 9292, 'ds_descricao': 'Moderado'}"
3,2371,"Estudo randomizado, multicêntrico, duplo cego,...",#000000,,Oxandrolona,2631.0,4157,NaN,2631.0,2025-03-17T15:41:45.000Z,...,None,None,"{'id': 824, 'ds_descricao': 'Respondido'}",None,None,"{'id': 914, 'ds_descricao': 'Aprovado'}",None,None,None,"{'id': 9292, 'ds_descricao': 'Moderado'}"
4,2372,"Estudo randomizado, multicêntrico, duplo cego,...",#000000,,Oxandrolona,2622.0,4166,3662.0,2631.0,2025-03-17T15:54:16.000Z,...,None,"{'id': 41, 'ds_descricao': 'Não'}","{'id': 824, 'ds_descricao': 'Respondido'}","{'id': 908, 'ds_descricao': 'Assinado'}",None,"{'id': 914, 'ds_descricao': 'Aprovado'}",None,None,None,"{'id': 9292, 'ds_descricao': 'Moderado'}"

In [25]:
centros = protocolo[['id','apelido_protocolo', 'numero_protocolo','co_externo','apelido_centro']].copy()
centros.head(5)

,id,apelido_protocolo,numero_protocolo,co_externo,apelido_centro
0,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed
1,1256,VISIONAIRE,,None,VISIONAIRE - SVRI Clínica Morumbi
2,1661,EsSCAPE-996,BIOTEST-996,None,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...
3,2371,Oxandrolona,,None,Oxandrolona - Unimed Brusque
4,2372,Oxandrolona,,None,Oxandrolona - Santa Casa de Santos

In [26]:
seguimento = agenda_df[['dados_participante', 'data_estimada', 'dados_status', 'dados_visita']].copy()

seguimento.loc[:, 'dados_participante_id'] = seguimento['dados_participante'].apply(lambda x: x['id'] if x is not None else None)
seguimento.loc[:, 'id_participante'] = seguimento['dados_participante'].apply(lambda x: x['id_participante'] if x is not None else None)
seguimento.loc[:, 'dados_protocolo'] = seguimento['dados_participante'].apply(lambda x: x['dados_protocolo'] if x is not None else None)

seguimento.loc[:, 'dados_status_id'] = seguimento['dados_status'].apply(lambda x: x['id'] if x is not None else None)
seguimento.loc[:, 'ds_descricao'] = seguimento['dados_status'].apply(lambda x: x['ds_descricao'] if x is not None else None)
seguimento.loc[:, 'ds_nome_visita'] = seguimento['dados_visita'].apply(lambda x: x['ds_nome_visita'] if x is not None else None)

seguimento.loc[:, 'apelido_protocolo'] = seguimento['dados_protocolo'].apply(lambda x: x['apelido_protocolo'] if x is not None else None)
seguimento['data_estimada'] = pd.to_datetime(seguimento['data_estimada'], errors='coerce')
seguimento.head(5)

,dados_participante,data_estimada,dados_status,dados_visita,dados_participante_id,id_participante,dados_protocolo,dados_status_id,ds_descricao,ds_nome_visita,apelido_protocolo
0,"{'id': 54, 'co_protocolo': 4, 'id_participante...",2021-01-05 00:00:00+00:00,"{'id': 20, 'ds_descricao': 'Realizada'}","{'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...",54,1001,"{'id': 4, 'apelido_protocolo': 'BTK', 'co_coor...",20,Realizada,Triagem,BTK
1,"{'id': 56, 'co_protocolo': 4, 'id_participante...",2021-01-07 00:00:00+00:00,"{'id': 20, 'ds_descricao': 'Realizada'}","{'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...",56,1002,"{'id': 4, 'apelido_protocolo': 'BTK', 'co_coor...",20,Realizada,Triagem,BTK
2,"{'id': 57, 'co_protocolo': 4, 'id_participante...",2021-01-08 00:00:00+00:00,"{'id': 20, 'ds_descricao': 'Realizada'}","{'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...",57,1003,"{'id': 4, 'apelido_protocolo': 'BTK', 'co_coor...",20,Realizada,Triagem,BTK
3,"{'id': 58, 'co_protocolo': 4, 'id_participante...",2021-01-12 00:00:00+00:00,"{'id': 20, 'ds_descricao': 'Realizada'}","{'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...",58,1004,"{'id': 4, 'apelido_protocolo': 'BTK', 'co_coor...",20,Realizada,Triagem,BTK
4,"{'id': 59, 'co_protocolo': 4, 'id_participante...",2021-01-14 00:00:00+00:00,"{'id': 20, 'ds_descricao': 'Realizada'}","{'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...",59,1005,"{'id': 4, 'apelido_protocolo': 'BTK', 'co_coor...",20,Realizada,Triagem,BTK

In [27]:
seguimento_tratado = seguimento.drop(['dados_participante','dados_status','id_participante','dados_status_id'], axis=1)
seguimento_tratado.loc[:, 'id'] = seguimento['dados_protocolo'].apply(lambda x: x['id'] if x is not None else None)
seguimento_tratado.head(5)

,data_estimada,dados_visita,dados_participante_id,dados_protocolo,ds_descricao,ds_nome_visita,apelido_protocolo,id
0,2021-01-05 00:00:00+00:00,"{'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...",54,"{'id': 4, 'apelido_protocolo': 'BTK', 'co_coor...",Realizada,Triagem,BTK,4
1,2021-01-07 00:00:00+00:00,"{'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...",56,"{'id': 4, 'apelido_protocolo': 'BTK', 'co_coor...",Realizada,Triagem,BTK,4
2,2021-01-08 00:00:00+00:00,"{'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...",57,"{'id': 4, 'apelido_protocolo': 'BTK', 'co_coor...",Realizada,Triagem,BTK,4
3,2021-01-12 00:00:00+00:00,"{'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...",58,"{'id': 4, 'apelido_protocolo': 'BTK', 'co_coor...",Realizada,Triagem,BTK,4
4,2021-01-14 00:00:00+00:00,"{'id': 1, 'ds_nome_visita': 'Triagem ', 'co_ex...",59,"{'id': 4, 'apelido_protocolo': 'BTK', 'co_coor...",Realizada,Triagem,BTK,4

In [28]:
seguimentos = pd.merge(centros, seguimento_tratado, on='id', how='inner')
seguimentos

,id,apelido_protocolo_x,numero_protocolo,co_externo,apelido_centro,data_estimada,dados_visita,dados_participante_id,dados_protocolo,ds_descricao,ds_nome_visita,apelido_protocolo_y
0,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,2026-01-16 00:00:00+00:00,"{'id': 3405, 'ds_nome_visita': 'Visita 1 - Tri...",3286,"{'id': 784, 'apelido_protocolo': 'SONATA-HCM',...",Realizada,Visita 1 - Triagem,SONATA-HCM
1,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,2026-01-16 00:00:00+00:00,"{'id': 3405, 'ds_nome_visita': 'Visita 1 - Tri...",3287,"{'id': 784, 'apelido_protocolo': 'SONATA-HCM',...",Realizada,Visita 1 - Triagem,SONATA-HCM
2,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,NaT,"{'id': 3412, 'ds_nome_visita': 'Visita de ence...",3287,"{'id': 784, 'apelido_protocolo': 'SONATA-HCM',...",Pendente,Visita de encerramento precoce,SONATA-HCM
3,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,NaT,"{'id': 3414, 'ds_nome_visita': 'Unscheduled', ...",3287,"{'id': 784, 'apelido_protocolo': 'SONATA-HCM',...",Pendente,Unscheduled,SONATA-HCM
4,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,2026-02-05 00:00:00+00:00,"{'id': 3406, 'ds_nome_visita': 'Visita 2 - Ran...",3287,"{'id': 784, 'apelido_protocolo': 'SONATA-HCM',...",Realizada,Visita 2 - Randomização,SONATA-HCM
...,...,...,...,...,...,...,...,...,...,...,...,...
1159,2622,NATURA,,NaN,NATURA - SVRI Clínica Santo André,2026-02-24 00:00:00+00:00,"{'id': 3590, 'ds_nome_visita': 'VS/V1', 'co_ex...",3364,"{'id': 2622, 'apelido_protocolo': 'NATURA', 'c...",Realizada,VS/V1,NATURA
1160,2622,NATURA,,NaN,NATURA - SVRI Clínica Santo André,2026-02-24 00:00:00+00:00,"{'id': 3593, 'ds_nome_visita': 'VR/V2', 'co_ex...",3364,"{'id': 2622, 'apelido_protocolo': 'NATURA', 'c...",Realizada,VR/V2,NATURA
1161,2622,NATURA,,NaN,NATURA - SVRI Clínica Santo André,2026-03-24 00:00:00+00:00,"{'id': 3594, 'ds_nome_visita': 'VF/V3 - Grupo ...",3364,"{'id': 2622, 'apelido_protocolo': 'NATURA', 'c...",Pendente,VF/V3 - Grupo Sérum Ultra Repositor,NATURA
1162,2622,NATURA,,NaN,NATURA - SVRI Clínica Santo André,2026-02-24 00:00:00+00:00,"{'id': 3590, 'ds_nome_visita': 'VS/V1', 'co_ex...",3365,"{'id': 2622, 'apelido_protocolo': 'NATURA', 'c...",Realizada,VS/V1,NATURA
1163,2622,NATURA,,NaN,NATURA - SVRI Clínica Santo André,2026-02-24 00:00:00+00:00,"{'id': 3593, 'ds_nome_visita': 'VR/V2', 'co_ex...",3365,"{'id': 2622, 'apelido_protocolo': 'NATURA', 'c...",Pendente,VR/V2,NATURA

In [29]:
seguimentos['apelido_protocolo_x'] = seguimentos['apelido_protocolo_x'].str.strip()
visitas_filtrado = seguimentos[seguimentos['ds_descricao'].str.contains('Pendente')]
nova_ordem = ["apelido_centro", "dados_participante_id", "ds_nome_visita","data_estimada","ds_descricao"]
visitas_reordenado = visitas_filtrado[nova_ordem].rename(
    columns={
        'apelido_centro':'Estudo/Centro',
        'dados_participante_id': 'ID Participante',
        'ds_nome_visita': 'Tipo Visita',
        'data_estimada':'Data Estimada',
        'ds_descricao':'Status'
    }
)
visitas_reordenado['Data Estimada'] = pd.to_datetime(visitas_reordenado['Data Estimada'], errors='coerce')
visitas_reordenado

,Estudo/Centro,ID Participante,Tipo Visita,Data Estimada,Status
2,SONATA-HCM - Clínica CardialMed,3287,Visita de encerramento precoce,NaT,Pendente
3,SONATA-HCM - Clínica CardialMed,3287,Unscheduled,NaT,Pendente
7,SONATA-HCM - Clínica CardialMed,3287,Visita 5 - Semana 12,2026-04-30 00:00:00+00:00,Pendente
8,SONATA-HCM - Clínica CardialMed,3287,Visita 6 - Semana 20,2026-06-25 00:00:00+00:00,Pendente
9,SONATA-HCM - Clínica CardialMed,3287,Visita 7 - Semana 26,2026-08-06 00:00:00+00:00,Pendente
...,...,...,...,...,...
1152,NATURA - SVRI Clínica Santo André,3348,VF/V3 - Grupo Trat. Intensivo Noturno,2026-03-23 00:00:00+00:00,Pendente
1155,NATURA - SVRI Clínica Santo André,3362,VF/V3 - Grupo Sérum Ultra Repositor,2026-03-24 00:00:00+00:00,Pendente
1158,NATURA - SVRI Clínica Santo André,3363,VF/V3 - Grupo Trat. Intensivo Noturno,2026-03-24 00:00:00+00:00,Pendente
1161,NATURA - SVRI Clínica Santo André,3364,VF/V3 - Grupo Sérum Ultra Repositor,2026-03-24 00:00:00+00:00,Pendente
1163,NATURA - SVRI Clínica Santo André,3365,VR/V2,2026-02-24 00:00:00+00:00,Pendente

In [30]:
datas_visitas = visitas_reordenado.copy()
datas_visitas['Data Estimada'] = pd.to_datetime(datas_visitas['Data Estimada'], errors='coerce')
datas_visitas = visitas_reordenado.dropna(subset=["Data Estimada"])
datas_visitas = datas_visitas.sort_values(by= "Data Estimada", ascending=True)
datas_visitas = datas_visitas[~datas_visitas["Tipo Visita"].isin(["Unscheduled", "Triagem", "End of Study"])]
valores_contagem = datas_visitas['Tipo Visita'].value_counts()
datas_visitas

,Estudo/Centro,ID Participante,Tipo Visita,Data Estimada,Status
267,Oxandrolona - Leforte HMCG,3333,VR/V2,2025-12-11 00:00:00+00:00,Pendente
282,Oxandrolona - Leforte HMCG,3334,VR/V2,2026-01-06 00:00:00+00:00,Pendente
259,Oxandrolona - Leforte HMCG,3302,2 semanas após a inserção do implante de oxand...,2026-02-12 00:00:00+00:00,Pendente
260,Oxandrolona - Leforte HMCG,3302,3 semanas após a inserção do implante de oxand...,2026-02-19 00:00:00+00:00,Pendente
291,Oxandrolona - Leforte HMCG,3355,VR/V2,2026-02-20 00:00:00+00:00,Pendente
...,...,...,...,...,...
988,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,3290,Visita 16,2028-11-30 00:00:00+00:00,Pendente
1032,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,3306,Visita 16,2029-01-01 00:00:00+00:00,Pendente
1051,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,3307,Visita 16,2029-01-08 00:00:00+00:00,Pendente
1065,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,3309,Visita 16,2029-01-09 00:00:00+00:00,Pendente
1079,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,3311,Visita 16,2029-01-11 00:00:00+00:00,Pendente

In [ ]:
def verificar_visitas_proximos_dias(datas_visitas, dias_para_visita=20):

    logger.info("Iniciando verificação de visitas futuras")

    if datas_visitas is None or datas_visitas.empty:
        logger.warning("DataFrame de visitas está vazio ou None")
        return pd.DataFrame()

    df = datas_visitas.copy()

    logger.info(f"Total de visitas recebidas: {len(df)}")

    df['Data Estimada'] = (
        pd.to_datetime(df['Data Estimada'], errors='coerce')
        .dt.tz_localize(None)
    )

    hoje = pd.Timestamp.today().normalize()
    limite_visita = hoje + pd.Timedelta(days=dias_para_visita)

    logger.info(f"Intervalo analisado: {hoje.date()} até {limite_visita.date()}")

    visitas_futuras = df[
        (df['Data Estimada'] >= hoje) &
        (df['Data Estimada'] <= limite_visita)
    ]

    logger.info(f"Visitas encontradas nos próximos {dias_para_visita} dias: {len(visitas_futuras)}")

    if visitas_futuras.empty:
        logger.info("Nenhuma visita encontrada dentro do intervalo")

    return visitas_futuras


visitas_20_dias = verificar_visitas_proximos_dias(datas_visitas, dias_para_visita=20)

logger.info(f"DataFrame final de visitas próximas possui {len(visitas_20_dias)} registros")

2026-03-12 16:41:26,372 | INFO | Iniciando verificação de visitas futuras
2026-03-12 16:41:26,373 | INFO | Total de visitas recebidas: 453
2026-03-12 16:41:26,377 | INFO | Intervalo analisado: 2026-03-12 até 2026-04-01
2026-03-12 16:41:26,378 | INFO | Visitas encontradas nos próximos 20 dias: 47
2026-03-12 16:41:26,380 | INFO | DataFrame final de visitas próximas possui 47 registros

In [ ]:
def enviar_emails_visitas(proximas_visitas):

    logger.info("Iniciando envio de email de visitas de seguimento")

    destinatarios = _parse_destinatarios(enviar_para)

    try:
        if proximas_visitas is None or proximas_visitas.empty:
            logger.info("Não há visitas nos próximos dias para enviar por e-mail.")
            return

        colunas_esperadas = ['Estudo/Centro', 'ID Participante', 'Tipo Visita', 'Data Estimada', 'Status']
        faltantes = [c for c in colunas_esperadas if c not in proximas_visitas.columns]
        if faltantes:
            logger.error(f"Colunas ausentes no DataFrame de visitas: {faltantes}")
            return

        if not all([smtp_server, email_usuario, email_senha, email_port]):
            logger.error("Configurações de e-mail estão incompletas.")
            return

        if not destinatarios:
            logger.warning("Nenhum destinatário válido para visitas. Email não enviado.")
            return

        tabela_html = proximas_visitas[colunas_esperadas].to_html(
            index=False, escape=False, justify="left", border=0, classes="table"
        )

        msg = MIMEMultipart("alternative")
        msg['From']    = email_usuario
        msg['To']      = email_usuario
        msg['Bcc']     = ', '.join(destinatarios)
        msg['Subject'] = "Visitas de Seguimento - próximos 20 dias"

        body = f"""
        <html>
            <head>{css_hover}</head>
            <body>
                <p>Olá,</p>
                <p>Segue abaixo lista com visitas de seguimento programadas para os próximos 20 dias.</p>
                {tabela_html}
                <p>Este email é gerado automaticamente a partir de informações inseridas na Polo Trial.</p>
                <p>Qualquer dúvida, por favor, contate o <strong><span style="text-decoration: underline;">time BI - SVRI</span></strong>.</p>
            </body>
        </html>
        """
        msg.attach(MIMEText(body, 'html'))

        logger.info(f"Conectando ao servidor SMTP {smtp_server}:{email_port}")

        with smtplib.SMTP(smtp_server, email_port) as server:
            server.starttls()
            server.login(email_usuario, email_senha)
            destinatarios_finais = [email_usuario] + destinatarios
            server.sendmail(email_usuario, destinatarios_finais, msg.as_string())
            logger.info("E-mail de visitas pendentes enviado com sucesso!")

    except Exception as e:
        logger.error(f"Erro ao enviar o e-mail de visitas: {e}", exc_info=True)


# Chamada da função
enviar_emails_visitas(visitas_20_dias)

E-mail de visitas pendentes enviado com sucesso!

**** Visitas de Monitoria

In [33]:
monitoria_df

,id,tipo_evento,titulo,ds_co_industria,ds_co_hc,co_participante,tipo,status_evento,data_estimada,data_estimada_fim,...,co_externo,data_limite_min,data_limite_max,data_ideal,dados_tipo,dados_status,dados_protocolo,dados_participante,dados_responsavel,dados_local
0,1,1,Centriguga,,,,4,20,2022-04-28T00:00:00.000Z,NaN,...,None,NaN,NaN,NaN,"{'id': 4, 'tipo': 'Calibração'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...",None,None,None,None
1,4,1,contrato V6,,,,6,20,2022-07-06T00:00:00.000Z,NaN,...,None,NaN,NaN,NaN,"{'id': 6, 'tipo': 'Contrato'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...","{'id': 53, 'apelido_protocolo': 'Dipro', 'co_c...",None,None,None
2,5,1,contrato_ Graviti,,,,6,20,2022-12-29T00:00:00.000Z,NaN,...,None,NaN,NaN,NaN,"{'id': 6, 'tipo': 'Contrato'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...","{'id': 322, 'apelido_protocolo': 'Graviti', 'c...",None,None,None
3,6,1,contrato_ Graviti,,,,6,20,2022-12-29T00:00:00.000Z,NaN,...,None,NaN,NaN,NaN,"{'id': 6, 'tipo': 'Contrato'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...","{'id': 322, 'apelido_protocolo': 'Graviti', 'c...",None,None,None
4,7,1,Vencimento GCP,,,,7,20,2025-08-16T00:00:00.000Z,2025-08-16T00:00:00.000Z,...,None,NaN,NaN,NaN,"{'id': 7, 'tipo': 'Vencimento GCP'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...",None,None,"{'id': 239, 'ds_nome': 'Caroline Pinheiro Vian...","{'id': 765, 'ds_descricao': 'Virtual'}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17915,41181,2,V19 - Semana 156,0761022-10016,0761022-10016,3316,1,18,2029-03-07T00:00:00.000Z,NaN,...,None,2029-02-28T00:00:00.000Z,2029-03-14T00:00:00.000Z,2029-03-07T00:00:00.000Z,"{'id': 1, 'tipo': 'Visita'}","{'id': 18, 'ds_descricao': 'Pendente', 'cor_st...","{'id': 584, 'apelido_protocolo': 'FREXALT', 'c...","{'id': 3316, 'id_participante': '0761022-10016...",None,None
17916,41182,2,Semana 14,502821-100130,100130,3260,1,389,2026-02-11T00:00:00.000Z,2026-02-11T00:00:00.000Z,...,None,2026-02-08T00:00:00.000Z,2026-02-14T00:00:00.000Z,2026-02-11T00:00:00.000Z,"{'id': 1, 'tipo': 'Visita'}","{'id': 389, 'ds_descricao': 'Não realizada', '...","{'id': 2229, 'apelido_protocolo': 'CS45570', '...","{'id': 3260, 'id_participante': '502821-100130...","{'id': 4238, 'ds_nome': 'Larissa Matias'}","{'id': 815, 'ds_descricao': 'SVRI'}"
17917,41183,2,Semana 16,502821-100130,100130,3260,1,389,2026-02-25T00:00:00.000Z,2026-02-25T00:00:00.000Z,...,None,2026-02-22T00:00:00.000Z,2026-02-28T00:00:00.000Z,2026-02-25T00:00:00.000Z,"{'id': 1, 'tipo': 'Visita'}","{'id': 389, 'ds_descricao': 'Não realizada', '...","{'id': 2229, 'apelido_protocolo': 'CS45570', '...","{'id': 3260, 'id_participante': '502821-100130...","{'id': 4238, 'ds_nome': 'Larissa Matias'}","{'id': 815, 'ds_descricao': 'SVRI'}"
17918,41184,2,VS/V1,93-22,NaN,3365,1,20,2026-02-24T00:00:00.000Z,NaN,...,None,NaN,NaN,NaN,"{'id': 1, 'tipo': 'Visita'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...","{'id': 2622, 'apelido_protocolo': 'NATURA', 'c...","{'id': 3365, 'id_participante': '93-22', 'ds_c...",None,None
17919,41185,2,VR/V2,93-22,NaN,3365,1,18,2026-02-24T00:00:00.000Z,NaN,...,None,2026-02-24T00:00:00.000Z,2026-03-03T00:00:00.000Z,2026-02-24T00:00:00.000Z,"{'id': 1, 'tipo': 'Visita'}","{'id': 18, 'ds_descricao': 'Pendente', 'cor_st...","{'id': 2622, 'apelido_protocolo': 'NATURA', 'c...","{'id': 3365, 'id_participante': '93-22', 'ds_c...",None,None

In [34]:
monitoria = monitoria_df[['dados_protocolo', 'dados_tipo', 'dados_status', 'data_estimada_filter']].copy()

monitoria.loc[:, 'dados_protocolo_id'] = monitoria['dados_protocolo'].apply(lambda x: x['id'] if x is not None else None)
monitoria.loc[:, 'apelido_protocolo'] = monitoria['dados_protocolo'].apply(lambda x: x['apelido_protocolo'] if x is not None else None)

monitoria.loc[:, 'dados_tipo_id'] = monitoria['dados_tipo'].apply(lambda x: x['id'] if x is not None else None)
monitoria.loc[:, 'dados_tipo_tipo'] = monitoria['dados_tipo'].apply(lambda x: x['tipo'] if x is not None else None)

monitoria.loc[:, 'dados_status_id'] = monitoria['dados_status'].apply(lambda x: x['id'] if x is not None else None)
monitoria.loc[:, 'ds_descricao'] = monitoria['dados_status'].apply(lambda x: x['ds_descricao'] if x is not None else None)

monitoria = monitoria.drop(['dados_protocolo','dados_status', 'dados_tipo_id','dados_status_id'], axis=1)
monitoria.rename(columns={'dados_protocolo_id': 'id'}, inplace=True)

monitoria.head(2)

,dados_tipo,data_estimada_filter,id,apelido_protocolo,dados_tipo_tipo,ds_descricao
0,"{'id': 4, 'tipo': 'Calibração'}",2022-04-28,NaN,NaN,Calibração,Realizada
1,"{'id': 6, 'tipo': 'Contrato'}",2022-07-06,53.0,Dipro,Contrato,Realizada

In [35]:
monitorias = pd.merge(centros, monitoria, on='id', how='inner')
monitorias

,id,apelido_protocolo_x,numero_protocolo,co_externo,apelido_centro,dados_tipo,data_estimada_filter,apelido_protocolo_y,dados_tipo_tipo,ds_descricao
0,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-02-13,SONATA-HCM,Monitoria,Realizada
1,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,"{'id': 1, 'tipo': 'Visita'}",2026-01-16,SONATA-HCM,Visita,Realizada
2,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,"{'id': 1, 'tipo': 'Visita'}",2026-01-16,SONATA-HCM,Visita,Realizada
3,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,"{'id': 1, 'tipo': 'Visita'}",NaN,SONATA-HCM,Visita,Pendente
4,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,"{'id': 1, 'tipo': 'Visita'}",NaN,SONATA-HCM,Visita,Pendente
...,...,...,...,...,...,...,...,...,...,...
1239,2622,NATURA,,NaN,NATURA - SVRI Clínica Santo André,"{'id': 1, 'tipo': 'Visita'}",2026-02-24,NATURA,Visita,Realizada
1240,2622,NATURA,,NaN,NATURA - SVRI Clínica Santo André,"{'id': 1, 'tipo': 'Visita'}",2026-03-24,NATURA,Visita,Pendente
1241,2622,NATURA,,NaN,NATURA - SVRI Clínica Santo André,"{'id': 1, 'tipo': 'Visita'}",2026-02-24,NATURA,Visita,Realizada
1242,2622,NATURA,,NaN,NATURA - SVRI Clínica Santo André,"{'id': 1, 'tipo': 'Visita'}",2026-02-24,NATURA,Visita,Pendente
1243,1168,DURAVELO-2,BT8009-230,None,DURAVELO-2 - Hospital do Capibaribe,"{'id': 2, 'tipo': 'Monitoria'}",2024-12-20,DURAVELO-2,Monitoria,Realizada

In [ ]:
monitorias_filtrado = monitorias[monitorias['dados_tipo_tipo'].str.contains('Monitoria')]
monitorias_filtrado['apelido_protocolo_x'] = monitorias_filtrado['apelido_protocolo_x'].str.strip()
monitorias_filtrado

,id,apelido_protocolo_x,numero_protocolo,co_externo,apelido_centro,dados_tipo,data_estimada_filter,apelido_protocolo_y,dados_tipo_tipo,ds_descricao
0,784,SONATA-HCM,LX4211.1-314-HCM,None,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-02-13,SONATA-HCM,Monitoria,Realizada
50,1661,EsSCAPE-996,BIOTEST-996,None,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2024-07-03,EsSCAPE-996,Monitoria,Realizada
51,1661,EsSCAPE-996,BIOTEST-996,None,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2025-07-24,EsSCAPE-996,Monitoria,Realizada
52,1661,EsSCAPE-996,BIOTEST-996,None,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2025-09-16,EsSCAPE-996,Monitoria,Realizada
53,1661,EsSCAPE-996,BIOTEST-996,None,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2025-09-25,EsSCAPE-996,Monitoria,Realizada
...,...,...,...,...,...,...,...,...,...,...
1155,1531,DLG,,PT1531,DLG - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-07-28,DLG,Monitoria,Realizada
1156,1531,DLG,,PT1531,DLG - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-12-08,DLG,Monitoria,Realizada
1187,2230,EASi-HF reduzido - 1378-0018,1378-0018,NaN,EASi-HF reduzido - 1378-0018 - Maternidade e C...,"{'id': 2, 'tipo': 'Monitoria'}",2025-10-23,EASi-HF reduzido - 1378-0018,Monitoria,Realizada
1188,2230,EASi-HF reduzido - 1378-0018,1378-0018,NaN,EASi-HF reduzido - 1378-0018 - Maternidade e C...,"{'id': 2, 'tipo': 'Monitoria'}",2026-03-20,EASi-HF reduzido - 1378-0018,Monitoria,Pendente
1243,1168,DURAVELO-2,BT8009-230,None,DURAVELO-2 - Hospital do Capibaribe,"{'id': 2, 'tipo': 'Monitoria'}",2024-12-20,DURAVELO-2,Monitoria,Realizada

In [ ]:
def verificar_monitorias_pendentes():

    logger.info("Iniciando verificação de monitorias pendentes")

    if monitorias_filtrado is None or monitorias_filtrado.empty:
        logger.warning("DataFrame monitorias_filtrado está vazio")
        return pd.DataFrame()

    df = monitorias_filtrado.copy()

    logger.info(f"Total de monitorias recebidas: {len(df)}")

    df['data_estimada_filter'] = (
        pd.to_datetime(df['data_estimada_filter'], errors='coerce')
        .dt.tz_localize(None)
    )

    hoje = pd.Timestamp.today().normalize()

    monitorias_pendentes = df[
        (df['ds_descricao'] == 'Pendente') &
        (df['data_estimada_filter'] >= hoje)
    ].sort_values('data_estimada_filter')

    logger.info(f"Monitorias pendentes encontradas: {len(monitorias_pendentes)}")

    colunas_monitoria = [
        'dados_tipo_tipo',
        'data_estimada_filter',
        'apelido_protocolo_x',
        'ds_descricao',
        'apelido_centro'
    ]

    if monitorias_pendentes.empty:

        logger.info("Nenhuma monitoria pendente encontrada")

    else:

        logger.info(
            "\nMonitorias pendentes:\n%s",
            monitorias_pendentes[colunas_monitoria]
        )

    return monitorias_pendentes

In [ ]:
# envio_para já foi definido na célula de variáveis de email (Cell 25)
logger.info(f"Destinatário monitoria configurado: {'sim' if envio_para else 'não'}")

In [39]:
monitorias_pendentes = verificar_monitorias_pendentes()
monitorias_pendentes.rename(columns={'apelido_centro':'Estudo/Centro', 'dados_tipo_tipo': 'Monitoria', 'data_estimada_filter': 'Data Estimada','ds_descricao': 'Status'}, inplace=True)
monitorias_pendentes

2026-03-12 16:41:27,217 | INFO | Iniciando verificação de monitorias pendentes
2026-03-12 16:41:27,217 | INFO | Total de monitorias recebidas: 80
2026-03-12 16:41:27,217 | INFO | Monitorias pendentes encontradas: 5
2026-03-12 16:41:27,217 | INFO |
Monitorias pendentes:
     dados_tipo_tipo data_estimada_filter           apelido_protocolo_x  \
342        Monitoria           2026-03-13               LIBREXIA-STROKE
1188       Monitoria           2026-03-20  EASi-HF reduzido - 1378-0018
59         Monitoria           2026-03-31                   EsSCAPE-996
743        Monitoria           2026-04-06           EASi-HF - 1378-0020
343        Monitoria           2026-04-09               LIBREXIA-STROKE

     ds_descricao                                     apelido_centro
342      Pendente  LIBREXIA-STROKE - Maternidade e Cirurgia Nossa...
1188     Pendente  EASi-HF reduzido - 1378-0018 - Maternidade e C...
59       Pendente  EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...
743      Pendente  EASi-HF - 1378-0020 - Maternidade e Cirurgia N...
343      Pendente  LIBREXIA-STROKE - Maternidade e Cirurgia Nossa...

,id,apelido_protocolo_x,numero_protocolo,co_externo,Estudo/Centro,dados_tipo,Data Estimada,apelido_protocolo_y,Monitoria,Status
342,169,LIBREXIA-STROKE,70033093STR3001,STRUCK,LIBREXIA-STROKE - Maternidade e Cirurgia Nossa...,"{'id': 2, 'tipo': 'Monitoria'}",2026-03-13,LIBREXIA-STROKE,Monitoria,Pendente
1188,2230,EASi-HF reduzido - 1378-0018,1378-0018,NaN,EASi-HF reduzido - 1378-0018 - Maternidade e C...,"{'id': 2, 'tipo': 'Monitoria'}",2026-03-20,EASi-HF reduzido - 1378-0018,Monitoria,Pendente
59,1661,EsSCAPE-996,BIOTEST-996,None,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2026-03-31,EsSCAPE-996,Monitoria,Pendente
743,655,EASi-HF - 1378-0020,1378-0020,PT655,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-04-06,EASi-HF - 1378-0020,Monitoria,Pendente
343,169,LIBREXIA-STROKE,70033093STR3001,STRUCK,LIBREXIA-STROKE - Maternidade e Cirurgia Nossa...,"{'id': 2, 'tipo': 'Monitoria'}",2026-04-09,LIBREXIA-STROKE,Monitoria,Pendente

In [40]:
monitoria_envio = monitorias_pendentes.drop(columns=['apelido_protocolo_x', 'co_externo', 'dados_tipo', 'apelido_protocolo_y'],errors='ignore')

monitoria_envio = monitoria_envio[
    [
        'Monitoria',
        'id',
        'numero_protocolo',
        'Estudo/Centro',
        'Data Estimada',
        'Status'
    ]
]
monitoria_envio

,Monitoria,id,numero_protocolo,Estudo/Centro,Data Estimada,Status
342,Monitoria,169,70033093STR3001,LIBREXIA-STROKE - Maternidade e Cirurgia Nossa...,2026-03-13,Pendente
1188,Monitoria,2230,1378-0018,EASi-HF reduzido - 1378-0018 - Maternidade e C...,2026-03-20,Pendente
59,Monitoria,1661,BIOTEST-996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,2026-03-31,Pendente
743,Monitoria,655,1378-0020,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,2026-04-06,Pendente
343,Monitoria,169,70033093STR3001,LIBREXIA-STROKE - Maternidade e Cirurgia Nossa...,2026-04-09,Pendente

In [ ]:
def enviar_emails_monitoria(monitoria_envio):

    logger.info("Iniciando rotina de envio de emails de monitoria")

    destinatarios = _parse_destinatarios(envio_para)

    try:
        if monitoria_envio is None or monitoria_envio.empty:
            logger.info("Não há monitorias pendentes para envio de email")
            return

        logger.info(f"Total de monitorias recebidas para envio: {len(monitoria_envio)}")

        colunas = ['Estudo/Centro', 'Monitoria', 'Data Estimada', 'Status']

        logger.info(f"Colunas do dataframe recebido: {monitoria_envio.columns.tolist()}")

        faltantes = [c for c in colunas if c not in monitoria_envio.columns]
        if faltantes:
            logger.error(f"Colunas ausentes no DataFrame de monitoria: {faltantes}")
            return

        tabela_html = monitoria_envio[colunas].to_html(
            index=False,
            escape=False,
            justify="left",
            border=0,
            classes="table"
        )

        logger.info("Tabela HTML de monitorias gerada")

        msg = MIMEMultipart("alternative")
        msg['From']    = email_usuario
        msg['To']      = email_usuario
        msg['Subject'] = "Visitas de Monitoria Pendentes"

        if not destinatarios:
            logger.warning("Nenhum destinatário válido para monitoria. Email não enviado.")
            return

        msg['Bcc'] = ', '.join(destinatarios)
        logger.info(f"Destinatários BCC: {destinatarios}")

        destinatarios_finais = [email_usuario] + destinatarios
        logger.info(f"Lista final de destinatários: {destinatarios_finais}")

        body = f"""
        <html>
            <head>{css_hover}</head>
            <body>
                <p>Olá,</p>
                <p>
                Segue abaixo lista com visitas de monitoria programadas
                para os próximos dias.
                </p>
                {tabela_html}
                <p>
                Este email é gerado automaticamente a partir de
                informações inseridas na Polo Trial.
                </p>
                <p>
                Qualquer dúvida, por favor, contate o
                <strong><span style="text-decoration: underline;">
                time BI - SVRI
                </span></strong>.
                </p>
            </body>
        </html>
        """

        msg.attach(MIMEText(body, 'html'))

        logger.info("Corpo do email criado")
        logger.info(f"Conectando ao servidor SMTP: {smtp_server}:{email_port}")

        with smtplib.SMTP(smtp_server, email_port) as server:
            server.starttls()
            logger.info("TLS iniciado")
            server.login(email_usuario, email_senha)
            logger.info("Login SMTP realizado")
            server.sendmail(email_usuario, destinatarios_finais, msg.as_string())
            logger.info("Email de monitoria enviado com sucesso")

    except Exception as e:
        logger.error(
            f"Erro ao enviar email de monitoria: {str(e)}",
            exc_info=True
        )


# chamada
enviar_emails_monitoria(monitoria_envio)

2026-03-12 16:41:27,276 | INFO | Iniciando rotina de envio de emails de monitoria
2026-03-12 16:41:27,277 | INFO | Total de monitorias recebidas para envio: 5
2026-03-12 16:41:27,277 | INFO | Colunas do dataframe recebido: ['Monitoria', 'id', 'numero_protocolo', 'Estudo/Centro', 'Data Estimada', 'Status']
2026-03-12 16:41:27,282 | INFO | Tabela HTML de monitorias gerada
2026-03-12 16:41:27,283 | WARNING | Variável envio_para não é lista. Nenhum destinatário definido.
2026-03-12 16:41:27,283 | INFO | Lista final de destinatários: ['gleice.barros@svriglobal.com']
2026-03-12 16:41:27,284 | INFO | Corpo do email criado
2026-03-12 16:41:27,285 | INFO | Conectando ao servidor SMTP: smtp.office365.com:587
2026-03-12 16:41:27,312 | INFO | TLS iniciado
2026-03-12 16:41:27,563 | INFO | Login SMTP realizado
2026-03-12 16:41:27,846 | INFO | Email de monitoria enviado com sucesso