In [1]:
import re
import requests
from urllib.parse import urljoin
import pandas as pd
import schedule
import time
from datetime import datetime, timedelta
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.base import MIMEBase
from email import encoders
import dotenv
from log_envios import registrar

*** Acesso a PoloTrial (API)

In [ ]:
#ROTA GERAL
dotenv.load_dotenv()

session = requests.Session()

polotrial_url = os.getenv("POLOTRIAL_URL")

if not polotrial_url:
    raise ValueError("POLOTRIAL_URL não definida")

payload = {
    "nome": os.getenv("POLOTRIAL_USER"),
    "password": os.getenv("POLOTRIAL_PASSWORD")
}

headers = {
    "Content-Type": "application/json"
}

session_url = f"{polotrial_url}/sessions"

try:
    login_response = requests.post(
        session_url,
        json=payload,
        headers=headers,
        timeout=30
    )
    login_response.raise_for_status()

except Exception as e:
    raise

auth_cookie = login_response.cookies.get("userId")

if not auth_cookie:
    raise Exception("Falha na autenticação")

endpoint_headers = {
    "cookie": f"userId={auth_cookie}"
}

if endpoint_headers['cookie']:
    print(endpoint_headers)
    print(polotrial_url)

{'cookie': 'userId=s%3AaPFB85Di3p_4H0JeSDJv80PNWBM4gK3b.Dk%2BtllqR5Tnh0rrVc67%2FYu0YHqe2jfdZ9zm7hkwLPz0'}
https://api.polotrial.com/beta

In [3]:
protocolo_url = f"{polotrial_url}/protocolo"

protocolos_ativos = [
    "161",  # Aguardando iniciação
    "39",   # Recrutamento aberto
    "9236", # Recrutamento aberto
    "9263", # Aguardando Ativação do Centro
    "393",  # Aguardando Ativação do Centro
    "9294", # Fase Contratual
    "819",  # Aguardando o Pacote Regulatório
    "739",  # Aprovação Anvisa
    "6",    # Aprovação Regulatória
    "912",  # Em apreciação ética
    "9163"  # Aprovado pelo CEP
]

df_protocolos = []

for co_status in protocolos_ativos:

    query_params = {
        "nested": "true",
        "status_protocolo": co_status
    }

    try:
        response = requests.get(
            protocolo_url,
            headers=endpoint_headers,
            params=query_params,
            timeout=30
        )

        response.raise_for_status()

        protocolo_json = response.json()

        if not protocolo_json:
            continue

        if isinstance(protocolo_json, dict):
            protocolo_json = [protocolo_json]

        df_temp = pd.DataFrame(protocolo_json)
        df_protocolos.append(df_temp)

    except Exception as e:
        print(f"Erro ao buscar protocolos para status {co_status}: {e}")

if df_protocolos:
    protocolos_dataframe = pd.concat(df_protocolos, ignore_index=True)
    print(f"DataFrame final de protocolos criado com {len(protocolos_dataframe)} registros")
else:
    print("Nenhum protocolo retornado pela API para os status consultados")

DataFrame final de protocolos criado com 38 registros

In [4]:
#ROTA PESSOAS
pessoas_url = f"{polotrial_url}/pessoas"

query_params = {
    "nested": "true",
}

try:
    response = requests.get(
        pessoas_url,
        headers=endpoint_headers,
        params=query_params,
        timeout=30
    )

    response.raise_for_status()

    pessoas = response.json()

    pessoas_df = pd.DataFrame(pessoas)

except Exception as e:
    raise

In [5]:
#ROTA AGENDA
agenda_url = f"{polotrial_url}/participante_visita"

query_params = {
    "nested": "true",
}

try:
    response = requests.get(
        agenda_url,
        headers=endpoint_headers,
        params=query_params,
        timeout=30
    )

    response.raise_for_status()

    agenda = response.json()

    agenda_df = pd.DataFrame(agenda)

except Exception as e:
    raise

In [6]:
particpantes_url = f"{polotrial_url}/participantes"

query_params = {
    "nested": "true",
}

try:
    response = requests.get(
        particpantes_url,
        headers=endpoint_headers,
        params=query_params,
        timeout=30
    )

    response.raise_for_status()

    participantes = response.json()

    if isinstance(participantes, dict):
        participantes = [participantes]

    participantes_df = pd.DataFrame(participantes)

except Exception as e:
    raise

In [7]:
monitoria_url = f"{polotrial_url}/agenda"

query_params = {
    "nested": "true",
}

try:
    response = requests.get(
        monitoria_url,
        headers=endpoint_headers,
        params=query_params,
        timeout=30
    )

    response.raise_for_status()

    monitoria = response.json()

    if isinstance(monitoria, dict):
        monitoria = [monitoria]

    monitoria_df = pd.DataFrame(monitoria)

except Exception as e:
    raise

*** Visualização e modelagem para extração de GCP (cadastros ativos)

In [8]:
pessoas_df.head(5)

,dados_ativo,id,ds_nome,co_tipo_gn,co_equipe_gn,co_formacao_maior_nivel_gn,dt_ultimo_certificado_gcp,registro_profissional,declaracao_confidencialidade,custo_mensal_estimado,...,user_id_log,dados_co_tipo_gn,dados_co_equipe_gn,dados_co_formacao_maior_nivel_gn,dados_status,dados_centro,dados_equipe_padrao_farmacia,dados_equipe_padrao_kits,dados_equipe_padrao,dados_pessoa_especialidade
0,{'descricao': 'Sim'},2978,NaN,562.0,None,NaN,NaN,NaN,None,None,...,None,"{'id': 562, 'ds_descricao': 'Equipe padrão (ad...",None,None,None,None,None,None,None,[]
1,{'descricao': 'Sim'},3545,NaN,562.0,None,NaN,NaN,NaN,None,None,...,None,"{'id': 562, 'ds_descricao': 'Equipe padrão (ad...",None,None,None,None,None,None,None,[]
2,{'descricao': 'Sim'},1332,,649.0,None,NaN,NaN,NaN,None,None,...,None,"{'id': 649, 'ds_descricao': 'Participante'}",None,None,None,None,None,None,None,[]
3,{'descricao': 'Sim'},3118,Alex Gonçalves Macedo,387.0,None,31.0,2023-09-06,74.334/SP,None,None,...,None,"{'id': 387, 'ds_descricao': 'Pesquisador Princ...",None,"{'id': 31, 'ds_descricao': 'Mestrado'}","{'id': 9404, 'ds_descricao': 'Ativo'}","{'id': 4, 'descricao': 'Santa Casa de Santos'}",None,None,None,"[{'id': 150, 'co_pessoa': 3118, 'co_pessoa_esp..."
4,{'descricao': 'Sim'},1554,Alex Vladimir Dudzic,649.0,None,NaN,NaN,NaN,None,None,...,None,"{'id': 649, 'ds_descricao': 'Participante'}",None,None,None,None,None,None,None,[]

In [9]:
colunas = [
    'dados_centro',
    'dt_ultimo_certificado_gcp',
    'ds_nome',
    'dados_co_tipo_gn',
    'dados_status'
]

faltantes = [c for c in colunas if c not in pessoas_df.columns]
if faltantes:
    raise Exception(f"Colunas ausentes: {faltantes}")
gcp = pessoas_df[colunas].copy()

gcp.loc[:, 'dados_centro_id'] = gcp['dados_centro'].apply(lambda x: x['id'] if x is not None else None)
gcp.loc[:, 'dados_centro_descricao'] = gcp['dados_centro'].apply(lambda x: x['descricao'] if x is not None else None)
gcp.loc[:, 'tipo_gn'] = gcp['dados_co_tipo_gn'].apply(lambda x: x['ds_descricao'] if x is not None else None)
gcp.loc[:, 'status'] = gcp['dados_status'].apply(lambda x: x['ds_descricao'] if x is not None else None)

gcp_ativos = gcp.drop(['dados_centro', 'dados_centro_id', 'dados_co_tipo_gn', 'dados_status'], axis=1)
gcp_modelado = gcp_ativos[gcp_ativos['status'] == 'Ativo']

gcp_modelado.head(5)

,dt_ultimo_certificado_gcp,ds_nome,dados_centro_descricao,tipo_gn,status
3,2023-09-06,Alex Gonçalves Macedo,Santa Casa de Santos,Pesquisador Principal,Ativo
5,NaN,Augusto Ferreira José,Santa Casa de Santos,Subinvestigador,Ativo
6,NaN,Dr. Ricardo Moro,Clinica de Ortopedia Campo Largo S/S LTDA,Pesquisador Principal,Ativo
374,NaN,Adão Castelo Antônio,Hospital Municipal de Barueri,Pesquisador Principal,Ativo
448,2025-06-26,Alessandro Vengjer,Santa Casa de Santos,Pesquisador Principal,Ativo

In [10]:
venc_gcp = gcp_modelado[gcp_modelado['tipo_gn'] != 'Equipe padrão (adicionada automaticamente para todos os protocolos)']
venc_gcp["Cadastro de data"] = venc_gcp["dt_ultimo_certificado_gcp"].apply(
    lambda x: "Não há data cadastrada" if pd.isna(x) else "Data cadastrada"
)

venc_gcp.rename(columns={'dt_ultimo_certificado_gcp': 'Assinatura do GCP', 'ds_nome': 'Nome', 'dados_centro_descricao': 'Centro','tipo_gn': 'Função', 'status': 'Status do Cadastro'}, inplace=True)

nova_ordem = ['Centro', 'Nome', 'Função','Status do Cadastro', 'Assinatura do GCP', "Cadastro de data"]
venc_gcp = venc_gcp[nova_ordem]
venc_gcp = venc_gcp.sort_values(by="Centro")
venc_gcp

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
1192,A2Z Clinical Centro Avancado De Pesquisa Clini...,Dr. Fernando Henrique de Carvalho Gouvêa,Equipe Médica,Ativo,NaN,Não há data cadastrada
1375,Centro Médico Sinapse,Dr. Ricardo Moutte de Freitas,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1285,Centro Vila Olimpia,Dr. Leandro Tuzuki Cavalheiro,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1413,Centro de Oncologia do Paraná,Dr. Thadeu Tiessi Suzuki,Pesquisador Principal,Ativo,2025-11-10,Data cadastrada
1190,Clin Kids,Dr. Fernando Bedoni,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
...,...,...,...,...,...,...
1894,NaN,Francine Heiko,Subinvestigador,Ativo,NaN,Não há data cadastrada
1896,NaN,Francine Heiko Alves Perpétuo,Subinvestigador,Ativo,NaN,Não há data cadastrada
2782,NaN,Marcelo Nagase,Financeiro,Ativo,NaN,Não há data cadastrada
3272,NaN,Nathalia de Oliveira Westphalen,Subinvestigador,Ativo,NaN,Não há data cadastrada
3385,NaN,Paula Sant' Anna,Subinvestigador,Ativo,NaN,Não há data cadastrada

In [11]:
hmcg = ['Leforte HMCG','Leforte Morumbi','Hospital Municipal de Barueri', 'Leforte Liberdade', 'Clínica CardialMed','Clínica CardialMed']
filtro1 = venc_gcp['Centro'].isin(hmcg)
venc_gcp_hmcg = venc_gcp[filtro1]
venc_gcp_hmcg=venc_gcp_hmcg.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_hmcg

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
1237,Clínica CardialMed,Dr. Heron Rhydan Saad Rached,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1560,Clínica CardialMed,Dra. Maristela Gomes de Almeida,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
2138,Clínica CardialMed,Heron Rhydan Saad Rached,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
2226,Clínica CardialMed,Izabella Cordeiro Freire Saad Rached,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
374,Hospital Municipal de Barueri,Adão Castelo Antônio,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
...,...,...,...,...,...,...
1195,Leforte Morumbi,Dr. Fernando Reis Menezes,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1562,Leforte Morumbi,Dra. Mayara de Almeida Rodrigues da Costa,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1595,Leforte Morumbi,Dra. Samantha Rodrigues Camargo Neves,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1872,Leforte Morumbi,Fernando Reis Menezes,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3028,Leforte Morumbi,Mayara de Almeida Rodrigues da Costa,Pesquisador Principal,Ativo,NaN,Não há data cadastrada

In [12]:
rocio = ['Maternidade e Cirurgia Nossa Senhora do Rocio SA']
filtro2 = venc_gcp['Centro'].isin(rocio)
venc_gcp_rocio = venc_gcp[filtro2]
venc_gcp_rocio=venc_gcp_rocio.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_rocio

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
596,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Andre Luiz Santos Cerneck,Subinvestigador,Ativo,2021-09-16,Data cadastrada
598,Maternidade e Cirurgia Nossa Senhora do Rocio SA,André Ricardo Fuck,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
747,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Brenno Giovanni Hernando Vidotti,Subinvestigador,Ativo,NaN,Não há data cadastrada
748,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Brenno Giovanni Hernando Vidotti,Subinvestigador,Ativo,NaN,Não há data cadastrada
827,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Carlos Alberto Kenji Nakashima,Subinvestigador,Ativo,NaN,Não há data cadastrada
889,Maternidade e Cirurgia Nossa Senhora do Rocio SA,César de Oliveira Lopes Dusilek,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
968,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dalton Luiz Rivabem Júnior,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
990,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Daniele Nogueira Rodrigues dos Santos,Subinvestigador,Ativo,NaN,Não há data cadastrada
998,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Danillo Taiguara Ramos Gomes da Silva,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1084,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Alvaro Viera Moura,Subinvestigador,Ativo,NaN,Não há data cadastrada
1090,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. André Ricardo Fuck,Pesquisador Principal,Ativo,2023-03-14,Data cadastrada
1117,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Carlos A. Kenji Nakashima,Subinvestigador,Ativo,NaN,Não há data cadastrada
1118,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Carlos Alberto Kenji Nakashima,Subinvestigador,Ativo,NaN,Não há data cadastrada
1132,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. César de Oliveira Lopes Dusilek,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1153,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Diego Carvalho Duarte Mari,Pesquisador Principal,Ativo,2022-09-06,Data cadastrada
1154,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Diego Roberto Rolim Vaciloto,Subinvestigador,Ativo,NaN,Não há data cadastrada
1189,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Felipe Fernandes Monteiro,Pesquisador Principal,Ativo,2020-08-21,Data cadastrada
1188,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Felipe Fernandes Monteiro,Subinvestigador,Ativo,NaN,Não há data cadastrada
1229,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Guilherme Vinicius de Andrade Barbosa,Equipe Médica,Ativo,2021-09-16,Data cadastrada
1257,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. João Guilherme de Toledo Justo,Subinvestigador,Ativo,NaN,Não há data cadastrada
1281,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Leandro Cardoso Canuto Vasconcelos,Subinvestigador,Ativo,NaN,Não há data cadastrada
1289,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Leonardo Ferreira Dias,Subinvestigador,Ativo,NaN,Não há data cadastrada
1376,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Ricardo Nascimento Riet,Subinvestigador,Ativo,2021-09-10,Data cadastrada
1380,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Ricardo Riet,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1388,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dr. Roberto Tauchmann,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1441,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dra. Amanda Pizzato da Silveira,Subinvestigador,Ativo,2021-06-21,Data cadastrada
1482,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dra. Daniele Nogueira Santos,Subinvestigador,Ativo,2021-06-06,Data cadastrada
1525,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dra. Juliana Graziele Nogueira Rodrigues dos S...,Subinvestigador,Ativo,2021-09-16,Data cadastrada
1534,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Dra. Lais Prigol Ruzzon,Subinvestigador,Ativo,NaN,Não há data cadastrada
1662,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Eduardo Hummelgen,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1816,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Fabiola Pedron Peres da Costa,Subinvestigador,Ativo,NaN,Não há data cadastrada
1815,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Fabiola Pedron Peres da Costa,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
2492,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Kengi Itinose,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
2668,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Lucas Roberto Rivabem Ferreira,Subinvestigador,Ativo,NaN,Não há data cadastrada
2753,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Maikele Ertel,Subinvestigador,Ativo,NaN,Não há data cadastrada
2787,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Marcelo Sávio Paiva Do Amaral Filho,Equipe Médica,Ativo,NaN,Não há data cadastrada
2788,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Marcelo Sávio Paiva do Amaral Filho,Subinvestigador,Ativo,NaN,Não há data cadastrada
3440,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Rafael Pasini Del Claro,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3524,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Ricardo Nascimento Riet,Subinvestigador,Ativo,NaN,Não há data cadastrada
3546,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Roberto Tauchmann,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3620,Maternidade e Cirurgia Nossa Senhora do Rocio SA,Rui Portes da Silva Filho,Subinvestigador,Ativo,NaN,Não há data cadastrada

In [13]:
iir_coord = ['Hospital das Clínicas de Itajubá', 'Saint-Beauté Clinique', 'Hospital Salvalus','Consultório Lopes e Sartorelli', 'Clínica Berger', 
            'QualiVida Higienópolis','Endolap Saúde' ]
filtro3 = venc_gcp['Centro'].isin(iir_coord)
venc_gcp_iir_coord = venc_gcp[filtro3] 
venc_gcp_iir_coord=venc_gcp_iir_coord.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_iir_coord

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
1133,Clínica Berger,Dr. Charles Berger,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3277,Consultório Lopes e Sartorelli,Nathalia Westphalen,Equipe Médica,Ativo,NaN,Não há data cadastrada

In [14]:
envio_viviane = ['Otorhinus Clínica Médica', 'Unimed Brusque']
filtro4 = venc_gcp['Centro'].isin(envio_viviane)
venc_gcp_envio_viviane = venc_gcp[filtro4]
venc_gcp_envio_viviane=venc_gcp_envio_viviane.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_envio_viviane

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
1355,Otorhinus Clínica Médica,Dr. Rafael Leonardo Emerich Lentz Martins,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3437,Otorhinus Clínica Médica,Rafael Leonardo Emerich Lentz Martins,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1097,Unimed Brusque,Dr. Antonio Carlos de Mattos Roxo,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1145,Unimed Brusque,Dr. Daniel Rodrigo Klein,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1180,Unimed Brusque,Dr. Fabio Benedetti,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1194,Unimed Brusque,Dr. Fernando Kamimoto Eckmann Helene,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1181,Unimed Brusque,Dr. Fábio Benedetti Rodrigues,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1230,Unimed Brusque,Dr. Gustavo Caon Loeff,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1244,Unimed Brusque,Dr. Ismael Paulo Búrigo,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1279,Unimed Brusque,Dr. Laércio Cadore,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1307,Unimed Brusque,Dr. Luiz Fernando Silveira Parrela,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1327,Unimed Brusque,Dr. Marcus Vitor Oliveira,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1347,Unimed Brusque,Dr. Paulo Cesar de Campos Ferreira,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1391,Unimed Brusque,Dr. Rodrigo Kraft Rovere,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1405,Unimed Brusque,Dr. Sebastião Dutra de Morais Júnior,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1411,Unimed Brusque,Dr. Sílvio Soares Nogueira,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1423,Unimed Brusque,Dr. Victor Daniel Schiocchet Monarim,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1446,Unimed Brusque,Dra. Ana Kris da Silva Sommariva,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1453,Unimed Brusque,Dra. Angelica Cristina da Silva Nóbrega,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1454,Unimed Brusque,Dra. Angelica Cristina dos Santos Nóbrega,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1455,Unimed Brusque,Dra. Anita Silva Brunel Alves,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1459,Unimed Brusque,Dra. Barbara Fiorentin Giordani Gamba,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1480,Unimed Brusque,Dra. Daniela Salvador Alves,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1499,Unimed Brusque,Dra. Fernanda Arns de Castro,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1559,Unimed Brusque,Dra. Marina Passos Seixas,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1561,Unimed Brusque,Dra. Marta Amaro da Silveira Duval,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
1597,Unimed Brusque,Dra. Sura Amélia Barbosa Félix Leão,Pesquisador Principal,Ativo,NaN,Não há data cadastrada

In [15]:
stacasa_santos = ['Santa Casa de Santos']
filtro5 = venc_gcp['Centro'].isin(stacasa_santos)
venc_gcp_stacasa_santos = venc_gcp[filtro5]
venc_gcp_stacasa_santos=venc_gcp_stacasa_santos.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_stacasa_santos

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
3,Santa Casa de Santos,Alex Gonçalves Macedo,Pesquisador Principal,Ativo,2023-09-06,Data cadastrada
5,Santa Casa de Santos,Augusto Ferreira José,Subinvestigador,Ativo,NaN,Não há data cadastrada
448,Santa Casa de Santos,Alessandro Vengjer,Pesquisador Principal,Ativo,2025-06-26,Data cadastrada
583,Santa Casa de Santos,André Galante Alencar Aranha,Pesquisador Principal,Ativo,2021-09-23,Data cadastrada
585,Santa Casa de Santos,André Gustavo Pereira Magalhães,Subinvestigador,Ativo,NaN,Não há data cadastrada
...,...,...,...,...,...,...
3544,Santa Casa de Santos,Roberto Higa Junior,Subinvestigador,Ativo,NaN,Não há data cadastrada
3634,Santa Casa de Santos,Samuel Brunini Petrarolha,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3635,Santa Casa de Santos,Samuel Brunini Petrarolha,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3939,Santa Casa de Santos,Vitor Hugo Straub,Pesquisador Principal,Ativo,NaN,Não há data cadastrada
3940,Santa Casa de Santos,Vitor Hugo Straub Canasiro,Pesquisador Principal,Ativo,NaN,Não há data cadastrada

In [16]:
capibaribe = ['Hospital do Capibaribe']
filtro6 = venc_gcp['Centro'].isin(capibaribe)
venc_gcp_capibaribe = venc_gcp[filtro6]
venc_gcp_capibaribe=venc_gcp_capibaribe.sort_values(by=['Centro', 'Nome'], ascending= [True, True])
venc_gcp_capibaribe

,Centro,Nome,Função,Status do Cadastro,Assinatura do GCP,Cadastro de data
1252,Hospital do Capibaribe,Dr. Jayme José Gouveia Filho,Equipe Médica,Ativo,2024-09-23,Data cadastrada
1557,Hospital do Capibaribe,Dra. Mariane Teodoro Fernandes Rodrigues,Pesquisador Principal,Ativo,2024-06-14,Data cadastrada
2942,Hospital do Capibaribe,Mariane Teodoro Fernandes Rodrigues,Pesquisador Principal,Ativo,NaN,Não há data cadastrada

***Função para cálculo da data de vencimento de GCP.

In [17]:
def verificar_vencimento_contratos(df_contratos, nome_centro, dias_para_vencimento=30):

    if df_contratos.empty:
        return df_contratos

    df_contratos = df_contratos.copy()

    df_contratos['Assinatura do GCP'] = pd.to_datetime(
        df_contratos['Assinatura do GCP'],
        errors='coerce'
    )

    hoje = datetime.today()
    limite_vencimento = hoje + timedelta(days=dias_para_vencimento)

    df_contratos['data_vencimento'] = (
        df_contratos['Assinatura do GCP'] + timedelta(days=2 * 365)
    )

    filtro_vencendo = (
        (df_contratos['data_vencimento'] > hoje) &
        (df_contratos['data_vencimento'] <= limite_vencimento)
    )

    filtro_sem_data = df_contratos['Assinatura do GCP'].isna()

    contratos_relevantes = df_contratos[filtro_vencendo | filtro_sem_data]

    return contratos_relevantes

In [18]:
contratos_hmcg = verificar_vencimento_contratos(venc_gcp_hmcg, "HMCG", dias_para_vencimento=30)
contratos_rocio = verificar_vencimento_contratos(venc_gcp_rocio, "Rocío", dias_para_vencimento=30)
contratos_iir_coord = verificar_vencimento_contratos(venc_gcp_iir_coord, "IRR COORD", dias_para_vencimento=30)
contratos_vivi = verificar_vencimento_contratos(venc_gcp_envio_viviane, "Envio Viviane", dias_para_vencimento=30)
contratos_stacsantos = verificar_vencimento_contratos(venc_gcp_stacasa_santos, "Santa Casa de Santos", dias_para_vencimento=30)
contratos_capibaribe = verificar_vencimento_contratos(venc_gcp_capibaribe, "Capibaribe", dias_para_vencimento=30)

***Função para envio dos emails de GCP

In [19]:
css_hover = """
<style>
/* Reset e fonte */
body, table, td, th, p {
    font-family: Arial, Helvetica, sans-serif;
    margin: 0;
    padding: 0;
}

/* Container do email */
.email-wrapper {
    background-color: #f4f6f4;
    padding: 24px;
}

/* Card principal */
.email-card {
    background-color: #ffffff;
    border-radius: 8px;
    padding: 28px 32px;
    max-width: 680px;
    margin: 0 auto;
    border: 1px solid #dde8d4;
}

/* Cabeçalho */
.email-header {
    border-bottom: 1px solid #dde8d4;
    padding-bottom: 16px;
    margin-bottom: 20px;
}

.email-header h2 {
    font-size: 17px;
    font-weight: 600;
    color: #1a2e1a;
    margin: 0 0 4px;
}

.email-header p {
    font-size: 12px;
    color: #6b7b6b;
    margin: 0;
}

/* Texto do corpo */
.email-body p {
    font-size: 14px;
    color: #3a4a3a;
    margin: 0 0 14px;
    line-height: 1.5;
}

/* Tabela */
table {
    border-collapse: collapse;
    width: 100%;
    font-size: 13px;
    margin-bottom: 24px;
}

th {
    background-color: #3B6D11;
    color: #ffffff;
    padding: 10px 12px;
    text-align: left;
    font-weight: 500;
    font-size: 12px;
    letter-spacing: 0.03em;
    border: none;
}

td {
    padding: 10px 12px;
    border-bottom: 1px solid #dde8d4;
    color: #1a1a1a;
    vertical-align: middle;
    text-align: left;
}

tr:nth-child(even) td {
    background-color: #f4f8f0;
}

tr:nth-child(odd) td {
    background-color: #ffffff;
}

/* Hover (funciona em Gmail/Web, ignorado no Outlook) */
tr:hover td {
    background-color: #e8f2de;
}

/* Rodapé */
.email-footer {
    border-top: 1px solid #dde8d4;
    padding-top: 16px;
    margin-top: 8px;
}

.email-footer p {
    font-size: 12px;
    color: #6b7b6b;
    margin: 0 0 4px;
    line-height: 1.5;
}

.email-footer strong {
    color: #3a4a3a;
}

/* Responsividade */
@media screen and (max-width: 600px) {
    .email-card { padding: 16px; }
    table { font-size: 12px; }
    th, td { padding: 8px; }
}
</style>
"""

Variáveis de envio de email

In [ ]:
smtp_server   = os.getenv("EMAIL_SERVER")
email_port    = int(os.getenv("EMAIL_PORT", "587").strip())
email_usuario = os.getenv("EMAIL_USERNAME")
email_senha   = os.getenv("EMAIL_PASSWORD")

# Destinatários GCP
enviar_para          = os.getenv("ENVIAR_PARA", "")
destinatario_hmcg    = os.getenv("DESTINATARIO_HMCG", "")
destinatario_rocio   = os.getenv("DESTINATARIO_ROCIO", "")
destinatario_scs     = os.getenv("DESTINATARIO_SCS", "")
destinatario_iir     = os.getenv("DESTINATARIO_IIR", "")
destinatario_vivi    = os.getenv("DESTINATARIO_VIVIANE", "")
destinatario_capibaribe = os.getenv("DESTINATARIO_CAPIBARIBE", "")

# Destinatário monitoria
envio_para = os.getenv("ENVIO_PARA", "")

# Validação das variáveis obrigatórias de SMTP
_vars_obrigatorias = {
    "EMAIL_SERVER": smtp_server,
    "EMAIL_USERNAME": email_usuario,
    "EMAIL_PASSWORD": email_senha,
}
_faltando = [k for k, v in _vars_obrigatorias.items() if not v]
if _faltando:
    raise ValueError(f"Variáveis ausentes no .env: {_faltando}")

def _parse_destinatarios(valor):
    """Converte string 'a@b.com,c@d.com' em lista de emails válidos."""
    email_regex = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    if not valor:
        return []
    emails = [e.strip() for e in valor.split(",") if e.strip()]
    validos = [e for e in emails if re.match(email_regex, e)]
    invalidos = set(emails) - set(validos)
    if invalidos:
        print(f"Emails ignorados por formato inválido: {invalidos}")
    return validos

In [21]:
def enviar_email(destinatarios, df_tratado, nome_grupo):

    if df_tratado is None or df_tratado.empty:
        registrar("Push Campo", nome_grupo, "PULADO", observacao="Sem registros")
        return

    try:
        if isinstance(destinatarios, str):
            destinatarios = _parse_destinatarios(destinatarios)
        else:
            destinatarios = _parse_destinatarios(", ".join([d for d in destinatarios if d]))

        if not destinatarios:
            registrar("Push Campo", nome_grupo, "PULADO", observacao="Nenhum destinatário válido")
            return

        colunas = [
            'Centro',
            'Nome',
            'Função',
            'Status do Cadastro',
            'Assinatura do GCP',
            'Cadastro de data'
        ]

        tabela_html = df_tratado[colunas].to_html(
            index=False,
            escape=False,
            border=0,
            justify="left",
            classes="table"
        )

        msg = MIMEMultipart("alternative")
        msg["From"]    = email_usuario
        msg["To"]      = email_usuario
        msg["Bcc"]     = ", ".join(destinatarios)
        msg["Subject"] = f"[{nome_grupo}] GCP sem data registrada ou com vencimento próximo"

        body = f"""
        <html>
            <head>{css_hover}</head>
            <body>
                <div class="email-wrapper">
                    <div class="email-card">
                        <div class="email-header">
                            <h2>Vencimento de GCP &mdash; {nome_grupo}</h2>
                            <p>GCP sem data registrada ou com vencimento próximo</p>
                        </div>
                        <div class="email-body">
                            <p>Bom dia,</p>
                            <p>Segue abaixo relação de GCPs que não possuem data registrada
                            no sistema ou que apresentam vencimento próximo:</p>
                        </div>
                        {tabela_html}
                        <div class="email-footer">
                            <p>Este e-mail é gerado automaticamente a partir de informações inseridas na <strong>Polo Trial</strong>.</p>
                            <p>Qualquer dúvida, contate o <strong>time BI - SVRI</strong>.</p>
                        </div>
                    </div>
                </div>
            </body>
        </html>
        """

        msg.attach(MIMEText(body, "html"))

        destinatarios_finais = [email_usuario] + destinatarios
        with smtplib.SMTP(smtp_server, email_port) as server:
            server.starttls()
            server.login(email_usuario, email_senha)
            server.sendmail(email_usuario, destinatarios_finais, msg.as_string())

        registrar(
            projeto="Push Campo",
            grupo=nome_grupo,
            status="ENVIADO",
            destinatarios=destinatarios_finais,
            num_registros=len(df_tratado),
        )

    except Exception as e:
        registrar("Push Campo", nome_grupo, "ERRO", observacao=str(e))
        print(f"{nome_grupo}: erro ao enviar email -> {str(e)}")

In [22]:
enviar_email([destinatario_hmcg], contratos_hmcg, "HMCG")
enviar_email([destinatario_rocio], contratos_rocio, "Rocio")
enviar_email([destinatario_iir], contratos_iir_coord, "IIR")
enviar_email([destinatario_scs], contratos_stacsantos, "Sta. Santos")
enviar_email([destinatario_vivi], contratos_vivi, "Viviane")
enviar_email([destinatario_capibaribe], contratos_capibaribe, "Capibaribe")

***Modelagem para envio de Visitas de Seguimento

In [23]:
protocolo = pd.DataFrame(protocolos_dataframe)
protocolo.head(5)

,id,titulo_protocolo,cor_agenda,numero_protocolo,apelido_protocolo,coordenador,pi,pesquisador_backup,co_pessoa_regulatorio,data_cadastro,...,dados_medicamento_do_estudo,dados_pendencias_regulatorio,dados_status_feasibility,dados_status_contrato,dados_status_orcamento,dados_status_regulatorio,dados_status_recrutamento,dados_status_financeiro,dados_assistente_de_pesquisa,dados_dificuldade_recrutamento
0,2305,Ensaio de plataforma de fase 2 para avaliar a ...,#d93f3f,SPY123-201,SKYLINE-UC (SPY123-201),2622.0,2384,None,2631.0,2025-02-20T14:20:48.000Z,...,None,None,"{'id': 824, 'ds_descricao': 'Respondido'}","{'id': 903, 'ds_descricao': 'Não recebido'}","{'id': 9171, 'ds_descricao': 'Aguardando envio '}","{'id': 918, 'ds_descricao': 'Em análise do CEP'}",None,None,None,"{'id': 9291, 'ds_descricao': 'Difícil'}"
1,234,"Um estudo multicêntrico, randomizado e aberto ...",#25a2c1,20190341,Code Break 202,2622.0,280,2829.0,214.0,2022-05-26T09:12:12.000Z,...,None,"{'id': 41, 'ds_descricao': 'Não'}","{'id': 824, 'ds_descricao': 'Respondido'}","{'id': 908, 'ds_descricao': 'Assinado'}","{'id': 877, 'ds_descricao': 'Aprovado'}","{'id': 914, 'ds_descricao': 'Aprovado'}","{'id': 936, 'ds_descricao': 'Recrutamento aber...",None,None,"{'id': 9291, 'ds_descricao': 'Difícil'}"
2,468,"Um estudo de Fase 3, prospectivo, randomizado,...",#cd4b13,TAK-330-3001,TAK-330-3001,2622.0,3136,NaN,214.0,2023-04-05T11:13:09.000Z,...,"{'id': 9311, 'ds_descricao': 'OCTAPLEX'}","{'id': 41, 'ds_descricao': 'Não'}","{'id': 824, 'ds_descricao': 'Respondido'}","{'id': 908, 'ds_descricao': 'Assinado'}","{'id': 877, 'ds_descricao': 'Aprovado'}","{'id': 914, 'ds_descricao': 'Aprovado'}","{'id': 936, 'ds_descricao': 'Recrutamento aber...","{'id': 9279, 'ds_descricao': 'Aprovado'}",None,"{'id': 9292, 'ds_descricao': 'Moderado'}"
3,655,"Um ensaio de fase III, duplo-cego, randomizado...",#01d3ef,1378-0020,EASi-HF - 1378-0020,2508.0,256,239.0,2807.0,2023-06-12T10:16:37.000Z,...,None,"{'id': 40, 'ds_descricao': 'Sim'}","{'id': 824, 'ds_descricao': 'Respondido'}","{'id': 908, 'ds_descricao': 'Assinado'}","{'id': 877, 'ds_descricao': 'Aprovado'}","{'id': 914, 'ds_descricao': 'Aprovado'}","{'id': 936, 'ds_descricao': 'Recrutamento aber...","{'id': 9279, 'ds_descricao': 'Aprovado'}",None,"{'id': 9292, 'ds_descricao': 'Moderado'}"
4,784,"Um estudo randomizado, duplo-cego, controlado ...",#000000,LX4211.1-314-HCM,SONATA-HCM,2829.0,271,NaN,4618.0,2023-07-17T10:14:16.000Z,...,None,"{'id': 40, 'ds_descricao': 'Sim'}","{'id': 824, 'ds_descricao': 'Respondido'}","{'id': 9, 'ds_descricao': 'Em negociação com o...",None,"{'id': 914, 'ds_descricao': 'Aprovado'}",None,None,None,"{'id': 9292, 'ds_descricao': 'Moderado'}"

In [24]:
centros = protocolo[['id','apelido_protocolo', 'numero_protocolo','co_externo','apelido_centro']].copy()
centros.head(5)

,id,apelido_protocolo,numero_protocolo,co_externo,apelido_centro
0,2305,SKYLINE-UC (SPY123-201),SPY123-201,SPY123-201,SKYLINE-UC (SPY123-201) - Santa Casa de Santos
1,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos
2,468,TAK-330-3001,TAK-330-3001,TAK 330-3001,TAK-330-3001 - Santa Casa de Santos
3,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...
4,784,SONATA-HCM,LX4211.1-314-HCM,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed

In [25]:
seguimento = agenda_df[['dados_participante', 'data_estimada', 'dados_status', 'dados_visita']].copy()

seguimento.loc[:, 'dados_participante_id'] = seguimento['dados_participante'].apply(lambda x: x['id'] if x is not None else None)
seguimento.loc[:, 'id_participante'] = seguimento['dados_participante'].apply(lambda x: x['id_participante'] if x is not None else None)
seguimento.loc[:, 'dados_protocolo'] = seguimento['dados_participante'].apply(lambda x: x['dados_protocolo'] if x is not None else None)

seguimento.loc[:, 'dados_status_id'] = seguimento['dados_status'].apply(lambda x: x['id'] if x is not None else None)
seguimento.loc[:, 'ds_descricao'] = seguimento['dados_status'].apply(lambda x: x['ds_descricao'] if x is not None else None)
seguimento.loc[:, 'ds_nome_visita'] = seguimento['dados_visita'].apply(lambda x: x['ds_nome_visita'] if x is not None else None)

seguimento.loc[:, 'apelido_protocolo'] = seguimento['dados_protocolo'].apply(lambda x: x['apelido_protocolo'] if x is not None else None)
seguimento['data_estimada'] = pd.to_datetime(seguimento['data_estimada'], errors='coerce')
seguimento.head(5)

,dados_participante,data_estimada,dados_status,dados_visita,dados_participante_id,id_participante,dados_protocolo,dados_status_id,ds_descricao,ds_nome_visita,apelido_protocolo
0,"{'id': 1706, 'co_protocolo': 105, 'id_particip...",2019-06-10 00:00:00+00:00,"{'id': 20, 'ds_descricao': 'Realizada'}","{'id': 588, 'ds_nome_visita': ' S1', 'co_exter...",1706,4308053001,"{'id': 105, 'apelido_protocolo': 'CLEAR Santa ...",20,Realizada,S1,CLEAR Santa Casa
1,"{'id': 1707, 'co_protocolo': 105, 'id_particip...",2019-06-17 00:00:00+00:00,"{'id': 20, 'ds_descricao': 'Realizada'}","{'id': 588, 'ds_nome_visita': ' S1', 'co_exter...",1707,4308054002,"{'id': 105, 'apelido_protocolo': 'CLEAR Santa ...",20,Realizada,S1,CLEAR Santa Casa
2,"{'id': 1708, 'co_protocolo': 105, 'id_particip...",2019-06-18 00:00:00+00:00,"{'id': 20, 'ds_descricao': 'Realizada'}","{'id': 588, 'ds_nome_visita': ' S1', 'co_exter...",1708,4308054003,"{'id': 105, 'apelido_protocolo': 'CLEAR Santa ...",20,Realizada,S1,CLEAR Santa Casa
3,"{'id': 1709, 'co_protocolo': 105, 'id_particip...",2019-05-15 00:00:00+00:00,"{'id': 20, 'ds_descricao': 'Realizada'}","{'id': 588, 'ds_nome_visita': ' S1', 'co_exter...",1709,4308053004,"{'id': 105, 'apelido_protocolo': 'CLEAR Santa ...",20,Realizada,S1,CLEAR Santa Casa
4,"{'id': 1706, 'co_protocolo': 105, 'id_particip...",2019-06-03 00:00:00+00:00,"{'id': 20, 'ds_descricao': 'Realizada'}","{'id': 589, 'ds_nome_visita': 'S2', 'co_extern...",1706,4308053001,"{'id': 105, 'apelido_protocolo': 'CLEAR Santa ...",20,Realizada,S2,CLEAR Santa Casa

In [26]:
seguimento_tratado = seguimento.drop(['dados_participante','dados_status','id_participante','dados_status_id'], axis=1)
seguimento_tratado.loc[:, 'id'] = seguimento['dados_protocolo'].apply(lambda x: x['id'] if x is not None else None)
seguimento_tratado.head(5)

,data_estimada,dados_visita,dados_participante_id,dados_protocolo,ds_descricao,ds_nome_visita,apelido_protocolo,id
0,2019-06-10 00:00:00+00:00,"{'id': 588, 'ds_nome_visita': ' S1', 'co_exter...",1706,"{'id': 105, 'apelido_protocolo': 'CLEAR Santa ...",Realizada,S1,CLEAR Santa Casa,105
1,2019-06-17 00:00:00+00:00,"{'id': 588, 'ds_nome_visita': ' S1', 'co_exter...",1707,"{'id': 105, 'apelido_protocolo': 'CLEAR Santa ...",Realizada,S1,CLEAR Santa Casa,105
2,2019-06-18 00:00:00+00:00,"{'id': 588, 'ds_nome_visita': ' S1', 'co_exter...",1708,"{'id': 105, 'apelido_protocolo': 'CLEAR Santa ...",Realizada,S1,CLEAR Santa Casa,105
3,2019-05-15 00:00:00+00:00,"{'id': 588, 'ds_nome_visita': ' S1', 'co_exter...",1709,"{'id': 105, 'apelido_protocolo': 'CLEAR Santa ...",Realizada,S1,CLEAR Santa Casa,105
4,2019-06-03 00:00:00+00:00,"{'id': 589, 'ds_nome_visita': 'S2', 'co_extern...",1706,"{'id': 105, 'apelido_protocolo': 'CLEAR Santa ...",Realizada,S2,CLEAR Santa Casa,105

In [27]:
seguimentos = pd.merge(centros, seguimento_tratado, on='id', how='inner')
seguimentos

,id,apelido_protocolo_x,numero_protocolo,co_externo,apelido_centro,data_estimada,dados_visita,dados_participante_id,dados_protocolo,ds_descricao,ds_nome_visita,apelido_protocolo_y
0,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,2024-12-03 00:00:00+00:00,"{'id': 2435, 'ds_nome_visita': 'Pré-Triagem co...",2944,"{'id': 234, 'apelido_protocolo': 'Code Break 2...",Realizada,Pré-Triagem com tecido de arquivo para PD-L1 I...,Code Break 202
1,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,2024-12-09 00:00:00+00:00,"{'id': 2435, 'ds_nome_visita': 'Pré-Triagem co...",2950,"{'id': 234, 'apelido_protocolo': 'Code Break 2...",Realizada,Pré-Triagem com tecido de arquivo para PD-L1 I...,Code Break 202
2,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,2025-04-29 00:00:00+00:00,"{'id': 2435, 'ds_nome_visita': 'Pré-Triagem co...",3041,"{'id': 234, 'apelido_protocolo': 'Code Break 2...",Realizada,Pré-Triagem com tecido de arquivo para PD-L1 I...,Code Break 202
3,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,2025-05-06 00:00:00+00:00,"{'id': 2249, 'ds_nome_visita': 'Pré-Triagem co...",3042,"{'id': 234, 'apelido_protocolo': 'Code Break 2...",Realizada,Pré-Triagem com biópsia nova para PD-L1 IHC e ...,Code Break 202
4,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,2025-11-24 00:00:00+00:00,"{'id': 2435, 'ds_nome_visita': 'Pré-Triagem co...",3272,"{'id': 234, 'apelido_protocolo': 'Code Break 2...",Realizada,Pré-Triagem com tecido de arquivo para PD-L1 I...,Code Break 202
...,...,...,...,...,...,...,...,...,...,...,...,...
1249,2651,Oxandrolona,,NaN,Oxandrolona - Centro de Oncologia do Paraná,NaT,"{'id': 3992, 'ds_nome_visita': 'Não Programada...",3396,"{'id': 2651, 'apelido_protocolo': 'Oxandrolona...",Pendente,Não Programada,Oxandrolona
1250,2651,Oxandrolona,,NaN,Oxandrolona - Centro de Oncologia do Paraná,NaT,"{'id': 3997, 'ds_nome_visita': 'VR/V2', 'co_ex...",3401,"{'id': 2651, 'apelido_protocolo': 'Oxandrolona...",Pendente,VR/V2,Oxandrolona
1251,2651,Oxandrolona,,NaN,Oxandrolona - Centro de Oncologia do Paraná,NaT,"{'id': 3998, 'ds_nome_visita': 'Data da Cirurg...",3401,"{'id': 2651, 'apelido_protocolo': 'Oxandrolona...",Pendente,Data da Cirurgia de LCA,Oxandrolona
1252,2651,Oxandrolona,,NaN,Oxandrolona - Centro de Oncologia do Paraná,NaT,"{'id': 3992, 'ds_nome_visita': 'Não Programada...",3404,"{'id': 2651, 'apelido_protocolo': 'Oxandrolona...",Pendente,Não Programada,Oxandrolona
1253,2651,Oxandrolona,,NaN,Oxandrolona - Centro de Oncologia do Paraná,NaT,"{'id': 3992, 'ds_nome_visita': 'Não Programada...",3405,"{'id': 2651, 'apelido_protocolo': 'Oxandrolona...",Pendente,Não Programada,Oxandrolona

In [28]:
seguimentos['apelido_protocolo_x'] = seguimentos['apelido_protocolo_x'].str.strip()
visitas_filtrado = seguimentos[seguimentos['ds_descricao'].str.contains('Pendente')]
nova_ordem = ["apelido_centro", "dados_participante_id", "ds_nome_visita","data_estimada","ds_descricao"]
visitas_reordenado = visitas_filtrado[nova_ordem].rename(
    columns={
        'apelido_centro':'Estudo/Centro',
        'dados_participante_id': 'ID Participante',
        'ds_nome_visita': 'Tipo Visita',
        'data_estimada':'Data Estimada',
        'ds_descricao':'Status'
    }
)
visitas_reordenado['Data Estimada'] = pd.to_datetime(visitas_reordenado['Data Estimada'], errors='coerce')
visitas_reordenado

,Estudo/Centro,ID Participante,Tipo Visita,Data Estimada,Status
8,Code Break 202 - Santa Casa de Santos,3377,Particularidades Financeiro,NaT,Pendente
9,Code Break 202 - Santa Casa de Santos,3377,Unscheduled Visit,NaT,Pendente
10,Code Break 202 - Santa Casa de Santos,3377,Pré-Triagem com biópsia nova para PD-L1 IHC e ...,NaT,Pendente
11,Code Break 202 - Santa Casa de Santos,3377,Triagem,NaT,Pendente
12,Code Break 202 - Santa Casa de Santos,3377,SFU,NaT,Pendente
...,...,...,...,...,...
1249,Oxandrolona - Centro de Oncologia do Paraná,3396,Não Programada,NaT,Pendente
1250,Oxandrolona - Centro de Oncologia do Paraná,3401,VR/V2,NaT,Pendente
1251,Oxandrolona - Centro de Oncologia do Paraná,3401,Data da Cirurgia de LCA,NaT,Pendente
1252,Oxandrolona - Centro de Oncologia do Paraná,3404,Não Programada,NaT,Pendente
1253,Oxandrolona - Centro de Oncologia do Paraná,3405,Não Programada,NaT,Pendente

In [29]:
datas_visitas = visitas_reordenado.copy()
datas_visitas['Data Estimada'] = pd.to_datetime(datas_visitas['Data Estimada'], errors='coerce')
datas_visitas = visitas_reordenado.dropna(subset=["Data Estimada"])
datas_visitas = datas_visitas.sort_values(by= "Data Estimada", ascending=True)
datas_visitas = datas_visitas[~datas_visitas["Tipo Visita"].isin(["Unscheduled", "Triagem", "End of Study"])]
valores_contagem = datas_visitas['Tipo Visita'].value_counts()
datas_visitas

,Estudo/Centro,ID Participante,Tipo Visita,Data Estimada,Status
970,Oxandrolona - Leforte HMCG,3333,VR/V2,2025-12-11 00:00:01+00:00,Pendente
972,Oxandrolona - Leforte HMCG,3330,VR/V2,2025-12-25 00:00:01+00:00,Pendente
1006,Oxandrolona - Leforte HMCG,3435,VR/V2,2026-03-01 00:00:01+00:00,Pendente
827,Oxandrolona - Santa Casa de Santos,3319,8 semanas após a inserção do implante de oxand...,2026-03-20 00:00:00+00:00,Pendente
826,Oxandrolona - Santa Casa de Santos,3323,VR/V2,2026-03-20 00:00:00+00:00,Pendente
...,...,...,...,...,...
486,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,3336,Visita 16,2029-01-18 00:00:00+00:00,Pendente
487,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,3387,Visita 16,2029-02-08 00:00:00+00:00,Pendente
735,EASi-HF reduzido - 1378-0018 - Maternidade e C...,3399,Visita 16,2029-02-15 00:00:00+00:00,Pendente
488,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,3434,Visita 16,2029-03-15 00:00:00+00:00,Pendente
489,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,3436,Visita 16,2029-03-27 00:00:00+00:00,Pendente

In [30]:
def verificar_visitas_proximos_dias(datas_visitas, dias_para_visita=20):

    if datas_visitas is None or datas_visitas.empty:
        return pd.DataFrame()

    df = datas_visitas.copy()

    df['Data Estimada'] = (
        pd.to_datetime(df['Data Estimada'], errors='coerce')
        .dt.tz_localize(None)
    )

    hoje = pd.Timestamp.today().normalize()
    limite_visita = hoje + pd.Timedelta(days=dias_para_visita)

    visitas_futuras = df[
        (df['Data Estimada'] >= hoje) &
        (df['Data Estimada'] <= limite_visita)
    ]

    return visitas_futuras

visitas_20_dias = verificar_visitas_proximos_dias(datas_visitas, dias_para_visita=20)

In [31]:
def enviar_emails_visitas(proximas_visitas):

    destinatarios = _parse_destinatarios(enviar_para)

    try:
        if proximas_visitas is None or proximas_visitas.empty:
            registrar("Push Campo", "Visitas", "PULADO", observacao="Sem visitas nos próximos 20 dias")
            return

        colunas_esperadas = ['Estudo/Centro', 'ID Participante', 'Tipo Visita', 'Data Estimada', 'Status']
        faltantes = [c for c in colunas_esperadas if c not in proximas_visitas.columns]
        if faltantes:
            registrar("Push Campo", "Visitas", "ERRO", observacao=f"Colunas ausentes: {faltantes}")
            return

        if not all([smtp_server, email_usuario, email_senha, email_port]):
            registrar("Push Campo", "Visitas", "ERRO", observacao="Configurações SMTP incompletas")
            return

        if not destinatarios:
            registrar("Push Campo", "Visitas", "PULADO", observacao="Nenhum destinatário válido")
            return

        tabela_html = proximas_visitas[colunas_esperadas].to_html(
            index=False, escape=False, justify="left", border=0, classes="table"
        )

        msg = MIMEMultipart("alternative")
        msg['From']    = email_usuario
        msg['To']      = email_usuario
        msg['Bcc']     = ', '.join(destinatarios)
        msg['Subject'] = "Visitas de Seguimento - próximos 20 dias"

        body = f"""
        <html>
            <head>{css_hover}</head>
            <body>
                <div class="email-wrapper">
                    <div class="email-card">
                        <div class="email-header">
                            <h2>Visitas de Seguimento</h2>
                            <p>Programadas para os próximos 20 dias</p>
                        </div>
                        <div class="email-body">
                            <p>Olá,</p>
                            <p>Segue abaixo lista com visitas de seguimento programadas para os próximos 20 dias.</p>
                        </div>
                        {tabela_html}
                        <div class="email-footer">
                            <p>Este e-mail é gerado automaticamente a partir de informações inseridas na <strong>Polo Trial</strong>.</p>
                            <p>Qualquer dúvida, contate o <strong>time BI - SVRI</strong>.</p>
                        </div>
                    </div>
                </div>
            </body>
        </html>
        """
        msg.attach(MIMEText(body, 'html'))

        destinatarios_finais = [email_usuario] + destinatarios
        with smtplib.SMTP(smtp_server, email_port) as server:
            server.starttls()
            server.login(email_usuario, email_senha)
            server.sendmail(email_usuario, destinatarios_finais, msg.as_string())

        registrar(
            projeto="Push Campo",
            grupo="Visitas",
            status="ENVIADO",
            destinatarios=destinatarios_finais,
            num_registros=len(proximas_visitas),
        )

    except Exception as e:
        registrar("Push Campo", "Visitas", "ERRO", observacao=str(e))
        print(f"Erro ao enviar email de visitas: {str(e)}")

# Chamada da função
enviar_emails_visitas(visitas_20_dias)

**** Visitas de Monitoria

In [32]:
monitoria_df

,id,tipo_evento,titulo,ds_co_industria,ds_co_hc,co_participante,tipo,status_evento,data_estimada,data_estimada_fim,...,data_limite_min,data_limite_max,data_ideal,ds_iniciais,dados_tipo,dados_status,dados_protocolo,dados_participante,dados_responsavel,dados_local
0,1,1,Centriguga,,,,4,20,2022-04-28T00:00:00.000Z,NaN,...,NaN,NaN,NaN,,"{'id': 4, 'tipo': 'Calibração'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...",None,None,None,None
1,4,1,contrato V6,,,,6,20,2022-07-06T00:00:00.000Z,NaN,...,NaN,NaN,NaN,,"{'id': 6, 'tipo': 'Contrato'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...","{'id': 53, 'apelido_protocolo': 'Dipro', 'co_c...",None,None,None
2,5,1,contrato_ Graviti,,,,6,20,2022-12-29T00:00:00.000Z,NaN,...,NaN,NaN,NaN,,"{'id': 6, 'tipo': 'Contrato'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...","{'id': 322, 'apelido_protocolo': 'Graviti', 'c...",None,None,None
3,6,1,contrato_ Graviti,,,,6,20,2022-12-29T00:00:00.000Z,NaN,...,NaN,NaN,NaN,,"{'id': 6, 'tipo': 'Contrato'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...","{'id': 322, 'apelido_protocolo': 'Graviti', 'c...",None,None,None
4,7,1,Vencimento GCP,,,,7,20,2025-08-16T00:00:00.000Z,2025-08-16T00:00:00.000Z,...,NaN,NaN,NaN,,"{'id': 7, 'tipo': 'Vencimento GCP'}","{'id': 20, 'ds_descricao': 'Realizada', 'cor_s...",None,None,"{'id': 239, 'ds_nome': 'Caroline Pinheiro Vian...","{'id': 765, 'ds_descricao': 'Virtual'}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18728,42535,2,Visita 12,1076012040,1076012,3436,1,18,2028-04-25T00:00:00.000Z,NaN,...,2028-04-04T00:00:00.000Z,2028-05-16T00:00:00.000Z,2028-04-25T00:00:00.000Z,M.G.S,"{'id': 1, 'tipo': 'Visita'}","{'id': 18, 'ds_descricao': 'Pendente', 'cor_st...","{'id': 655, 'apelido_protocolo': 'EASi-HF - 13...","{'id': 3436, 'id_participante': '1076012040', ...",None,None
18729,42536,2,Visita 13,1076012040,1076012,3436,1,18,2028-07-18T00:00:00.000Z,NaN,...,2028-06-27T00:00:00.000Z,2028-08-08T00:00:00.000Z,2028-07-18T00:00:00.000Z,M.G.S,"{'id': 1, 'tipo': 'Visita'}","{'id': 18, 'ds_descricao': 'Pendente', 'cor_st...","{'id': 655, 'apelido_protocolo': 'EASi-HF - 13...","{'id': 3436, 'id_participante': '1076012040', ...",None,None
18730,42537,2,Visita 14,1076012040,1076012,3436,1,18,2028-10-10T00:00:00.000Z,NaN,...,2028-09-19T00:00:00.000Z,2028-10-31T00:00:00.000Z,2028-10-10T00:00:00.000Z,M.G.S,"{'id': 1, 'tipo': 'Visita'}","{'id': 18, 'ds_descricao': 'Pendente', 'cor_st...","{'id': 655, 'apelido_protocolo': 'EASi-HF - 13...","{'id': 3436, 'id_participante': '1076012040', ...",None,None
18731,42538,2,Visita 15,1076012040,1076012,3436,1,18,2029-01-02T00:00:00.000Z,NaN,...,2028-12-12T00:00:00.000Z,2029-01-23T00:00:00.000Z,2029-01-02T00:00:00.000Z,M.G.S,"{'id': 1, 'tipo': 'Visita'}","{'id': 18, 'ds_descricao': 'Pendente', 'cor_st...","{'id': 655, 'apelido_protocolo': 'EASi-HF - 13...","{'id': 3436, 'id_participante': '1076012040', ...",None,None
18732,42539,2,Visita 16,1076012040,1076012,3436,1,18,2029-03-27T00:00:00.000Z,NaN,...,2029-03-06T00:00:00.000Z,2029-04-17T00:00:00.000Z,2029-03-27T00:00:00.000Z,M.G.S,"{'id': 1, 'tipo': 'Visita'}","{'id': 18, 'ds_descricao': 'Pendente', 'cor_st...","{'id': 655, 'apelido_protocolo': 'EASi-HF - 13...","{'id': 3436, 'id_participante': '1076012040', ...",None,None

In [33]:
monitoria = monitoria_df[['dados_protocolo', 'dados_tipo', 'dados_status', 'data_estimada_filter']].copy()

monitoria.loc[:, 'dados_protocolo_id'] = monitoria['dados_protocolo'].apply(lambda x: x['id'] if x is not None else None)
monitoria.loc[:, 'apelido_protocolo'] = monitoria['dados_protocolo'].apply(lambda x: x['apelido_protocolo'] if x is not None else None)

monitoria.loc[:, 'dados_tipo_id'] = monitoria['dados_tipo'].apply(lambda x: x['id'] if x is not None else None)
monitoria.loc[:, 'dados_tipo_tipo'] = monitoria['dados_tipo'].apply(lambda x: x['tipo'] if x is not None else None)

monitoria.loc[:, 'dados_status_id'] = monitoria['dados_status'].apply(lambda x: x['id'] if x is not None else None)
monitoria.loc[:, 'ds_descricao'] = monitoria['dados_status'].apply(lambda x: x['ds_descricao'] if x is not None else None)

monitoria = monitoria.drop(['dados_protocolo','dados_status', 'dados_tipo_id','dados_status_id'], axis=1)
monitoria.rename(columns={'dados_protocolo_id': 'id'}, inplace=True)

monitoria.head(2)

,dados_tipo,data_estimada_filter,id,apelido_protocolo,dados_tipo_tipo,ds_descricao
0,"{'id': 4, 'tipo': 'Calibração'}",2022-04-28,NaN,NaN,Calibração,Realizada
1,"{'id': 6, 'tipo': 'Contrato'}",2022-07-06,53.0,Dipro,Contrato,Realizada

In [34]:
monitorias = pd.merge(centros, monitoria, on='id', how='inner')
monitorias

,id,apelido_protocolo_x,numero_protocolo,co_externo,apelido_centro,dados_tipo,data_estimada_filter,apelido_protocolo_y,dados_tipo_tipo,ds_descricao
0,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-02-03,Code Break 202,Monitoria,Realizada
1,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-08-04,Code Break 202,Monitoria,Realizada
2,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-11-11,Code Break 202,Monitoria,Realizada
3,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2026-03-30,Code Break 202,Monitoria,Realizada
4,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,"{'id': 1, 'tipo': 'Visita'}",2024-12-03,Code Break 202,Visita,Realizada
...,...,...,...,...,...,...,...,...,...,...
1307,2651,Oxandrolona,,NaN,Oxandrolona - Centro de Oncologia do Paraná,"{'id': 1, 'tipo': 'Visita'}",NaN,Oxandrolona,Visita,Pendente
1308,2651,Oxandrolona,,NaN,Oxandrolona - Centro de Oncologia do Paraná,"{'id': 1, 'tipo': 'Visita'}",2026-06-08,Oxandrolona,Visita,Pendente
1309,2651,Oxandrolona,,NaN,Oxandrolona - Centro de Oncologia do Paraná,"{'id': 1, 'tipo': 'Visita'}",2026-08-03,Oxandrolona,Visita,Pendente
1310,2651,Oxandrolona,,NaN,Oxandrolona - Centro de Oncologia do Paraná,"{'id': 1, 'tipo': 'Visita'}",2026-10-26,Oxandrolona,Visita,Pendente
1311,2651,Oxandrolona,,NaN,Oxandrolona - Centro de Oncologia do Paraná,"{'id': 1, 'tipo': 'Visita'}",NaN,Oxandrolona,Visita,Pendente

In [35]:
monitorias_filtrado = monitorias[monitorias['dados_tipo_tipo'].str.contains('Monitoria')]
monitorias_filtrado['apelido_protocolo_x'] = monitorias_filtrado['apelido_protocolo_x'].str.strip()
monitorias_filtrado

,id,apelido_protocolo_x,numero_protocolo,co_externo,apelido_centro,dados_tipo,data_estimada_filter,apelido_protocolo_y,dados_tipo_tipo,ds_descricao
0,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-02-03,Code Break 202,Monitoria,Realizada
1,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-08-04,Code Break 202,Monitoria,Realizada
2,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-11-11,Code Break 202,Monitoria,Realizada
3,234,Code Break 202,20190341,20190341,Code Break 202 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2026-03-30,Code Break 202,Monitoria,Realizada
18,468,TAK-330-3001,TAK-330-3001,TAK 330-3001,TAK-330-3001 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-03-06,TAK-330-3001,Monitoria,Realizada
19,468,TAK-330-3001,TAK-330-3001,TAK 330-3001,TAK-330-3001 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-05-13,TAK-330-3001,Monitoria,Realizada
20,468,TAK-330-3001,TAK-330-3001,TAK 330-3001,TAK-330-3001 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-05-13,TAK-330-3001,Monitoria,Realizada
21,468,TAK-330-3001,TAK-330-3001,TAK 330-3001,TAK-330-3001 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-08-05,TAK-330-3001,Monitoria,Realizada
22,468,TAK-330-3001,TAK-330-3001,TAK 330-3001,TAK-330-3001 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-10-17,TAK-330-3001,Monitoria,Realizada
23,468,TAK-330-3001,TAK-330-3001,TAK 330-3001,TAK-330-3001 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-09-26,TAK-330-3001,Monitoria,Realizada
24,468,TAK-330-3001,TAK-330-3001,TAK 330-3001,TAK-330-3001 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2026-01-08,TAK-330-3001,Monitoria,Realizada
25,468,TAK-330-3001,TAK-330-3001,TAK 330-3001,TAK-330-3001 - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2026-04-02,TAK-330-3001,Monitoria,Realizada
76,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2023-11-30,EASi-HF - 1378-0020,Monitoria,Realizada
77,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2025-05-09,EASi-HF - 1378-0020,Monitoria,Realizada
78,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2025-07-01,EASi-HF - 1378-0020,Monitoria,Realizada
79,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2025-09-10,EASi-HF - 1378-0020,Monitoria,Realizada
80,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2025-09-22,EASi-HF - 1378-0020,Monitoria,Realizada
81,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2025-08-27,EASi-HF - 1378-0020,Monitoria,Realizada
82,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2025-10-22,EASi-HF - 1378-0020,Monitoria,Realizada
83,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2025-11-17,EASi-HF - 1378-0020,Monitoria,Realizada
84,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2025-12-16,EASi-HF - 1378-0020,Monitoria,Realizada
85,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-01-09,EASi-HF - 1378-0020,Monitoria,Realizada
86,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-02-26,EASi-HF - 1378-0020,Monitoria,Realizada
87,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-01-14,EASi-HF - 1378-0020,Monitoria,Realizada
88,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-03-05,EASi-HF - 1378-0020,Monitoria,Realizada
89,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-04-06,EASi-HF - 1378-0020,Monitoria,Realizada
90,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-05-28,EASi-HF - 1378-0020,Monitoria,Pendente
91,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-05-11,EASi-HF - 1378-0020,Monitoria,Realizada
92,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-06-10,EASi-HF - 1378-0020,Monitoria,Pendente
590,784,SONATA-HCM,LX4211.1-314-HCM,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-02-13,SONATA-HCM,Monitoria,Realizada
591,784,SONATA-HCM,LX4211.1-314-HCM,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-07-07,SONATA-HCM,Monitoria,Pendente
592,784,SONATA-HCM,LX4211.1-314-HCM,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-11-17,SONATA-HCM,Monitoria,Pendente
593,784,SONATA-HCM,LX4211.1-314-HCM,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-11-17,SONATA-HCM,Monitoria,Pendente
594,784,SONATA-HCM,LX4211.1-314-HCM,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-11-17,SONATA-HCM,Monitoria,Pendente
659,1531,DLG,,DLG,DLG - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-05-30,DLG,Monitoria,Realizada
660,1531,DLG,,DLG,DLG - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-07-28,DLG,Monitoria,Realizada
661,1531,DLG,,DLG,DLG - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-12-08,DLG,Monitoria,Realizada
662,1531,DLG,,DLG,DLG - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2026-04-27,DLG,Monitoria,Realizada
663,1531,DLG,,DLG,DLG - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2026-04-28,DLG,Monitoria,Realizada
696,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2024-07-03,EsSCAPE-996,Monitoria,Realizada
697,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2025-07-24,EsSCAPE-996,Monitoria,Realizada
698,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2025-09-16,EsSCAPE-996,Monitoria,Realizada
699,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2025-09-25,EsSCAPE-996,Monitoria,Realizada
700,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2025-10-24,EsSCAPE-996,Monitoria,Realizada
701,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2025-12-04,EsSCAPE-996,Monitoria,Realizada
702,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2025-12-19,EsSCAPE-996,Monitoria,Realizada
703,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2026-01-23,EsSCAPE-996,Monitoria,Realizada
704,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2026-02-20,EsSCAPE-996,Monitoria,Realizada
705,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2026-02-26,EsSCAPE-996,Monitoria,Realizada
706,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2026-06-26,EsSCAPE-996,Monitoria,Pendente
707,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2026-05-25,EsSCAPE-996,Monitoria,Realizada
708,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2026-06-23,EsSCAPE-996,Monitoria,Pendente
755,2230,EASi-HF reduzido - 1378-0018,1378-0018,1378-0018,EASi-HF reduzido - 1378-0018 - Maternidade e C...,"{'id': 2, 'tipo': 'Monitoria'}",2025-10-23,EASi-HF reduzido - 1378-0018,Monitoria,Realizada
756,2230,EASi-HF reduzido - 1378-0018,1378-0018,1378-0018,EASi-HF reduzido - 1378-0018 - Maternidade e C...,"{'id': 2, 'tipo': 'Monitoria'}",2026-03-20,EASi-HF reduzido - 1378-0018,Monitoria,Realizada
794,2372,Oxandrolona,,NaN,Oxandrolona - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2025-12-29,Oxandrolona,Monitoria,Realizada
795,2372,Oxandrolona,,NaN,Oxandrolona - Santa Casa de Santos,"{'id': 2, 'tipo': 'Monitoria'}",2026-04-16,Oxandrolona,Monitoria,Realizada

In [36]:
def verificar_monitorias_pendentes():

    if monitorias_filtrado is None or monitorias_filtrado.empty:
        return pd.DataFrame()

    df = monitorias_filtrado.copy()

    df['data_estimada_filter'] = (
        pd.to_datetime(df['data_estimada_filter'], errors='coerce')
        .dt.tz_localize(None)
    )

    hoje = pd.Timestamp.today().normalize()

    monitorias_pendentes = df[
        (df['ds_descricao'] == 'Pendente') &
        (df['data_estimada_filter'] >= hoje)
    ].sort_values('data_estimada_filter')

    return monitorias_pendentes

In [37]:
monitorias_pendentes = verificar_monitorias_pendentes()
monitorias_pendentes.rename(columns={'apelido_centro':'Estudo/Centro', 'dados_tipo_tipo': 'Monitoria', 'data_estimada_filter': 'Data Estimada','ds_descricao': 'Status'}, inplace=True)
monitorias_pendentes

,id,apelido_protocolo_x,numero_protocolo,co_externo,Estudo/Centro,dados_tipo,Data Estimada,apelido_protocolo_y,Monitoria,Status
90,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-05-28,EASi-HF - 1378-0020,Monitoria,Pendente
92,655,EASi-HF - 1378-0020,1378-0020,EASI HF,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,"{'id': 2, 'tipo': 'Monitoria'}",2026-06-10,EASi-HF - 1378-0020,Monitoria,Pendente
708,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2026-06-23,EsSCAPE-996,Monitoria,Pendente
706,1661,EsSCAPE-996,BIOTEST-996,996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,"{'id': 2, 'tipo': 'Monitoria'}",2026-06-26,EsSCAPE-996,Monitoria,Pendente
591,784,SONATA-HCM,LX4211.1-314-HCM,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-07-07,SONATA-HCM,Monitoria,Pendente
592,784,SONATA-HCM,LX4211.1-314-HCM,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-11-17,SONATA-HCM,Monitoria,Pendente
593,784,SONATA-HCM,LX4211.1-314-HCM,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-11-17,SONATA-HCM,Monitoria,Pendente
594,784,SONATA-HCM,LX4211.1-314-HCM,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,"{'id': 2, 'tipo': 'Monitoria'}",2026-11-17,SONATA-HCM,Monitoria,Pendente

In [38]:
monitoria_envio = monitorias_pendentes.drop(columns=['apelido_protocolo_x', 'co_externo', 'dados_tipo', 'apelido_protocolo_y'],errors='ignore')

monitoria_envio = monitoria_envio[
    [
        'Monitoria',
        'id',
        'numero_protocolo',
        'Estudo/Centro',
        'Data Estimada',
        'Status'
    ]
]
monitoria_envio

,Monitoria,id,numero_protocolo,Estudo/Centro,Data Estimada,Status
90,Monitoria,655,1378-0020,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,2026-05-28,Pendente
92,Monitoria,655,1378-0020,EASi-HF - 1378-0020 - Maternidade e Cirurgia N...,2026-06-10,Pendente
708,Monitoria,1661,BIOTEST-996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,2026-06-23,Pendente
706,Monitoria,1661,BIOTEST-996,EsSCAPE-996 - Maternidade e Cirurgia Nossa Sen...,2026-06-26,Pendente
591,Monitoria,784,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,2026-07-07,Pendente
592,Monitoria,784,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,2026-11-17,Pendente
593,Monitoria,784,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,2026-11-17,Pendente
594,Monitoria,784,LX4211.1-314-HCM,SONATA-HCM - Clínica CardialMed,2026-11-17,Pendente

In [39]:
def enviar_emails_monitoria(monitoria_envio):

    destinatarios = _parse_destinatarios(envio_para)

    try:
        if monitoria_envio is None or monitoria_envio.empty:
            registrar("Push Campo", "Monitoria", "PULADO", observacao="Sem monitorias pendentes")
            return

        colunas = ['Estudo/Centro', 'Monitoria', 'Data Estimada', 'Status']

        faltantes = [c for c in colunas if c not in monitoria_envio.columns]
        if faltantes:
            registrar("Push Campo", "Monitoria", "ERRO", observacao=f"Colunas ausentes: {faltantes}")
            return

        if not destinatarios:
            registrar("Push Campo", "Monitoria", "PULADO", observacao="Nenhum destinatário válido")
            return

        tabela_html = monitoria_envio[colunas].to_html(
            index=False,
            escape=False,
            justify="left",
            border=0,
            classes="table"
        )

        msg = MIMEMultipart("alternative")
        msg['From']    = email_usuario
        msg['To']      = email_usuario
        msg['Subject'] = "Visitas de Monitoria Pendentes"
        msg['Bcc'] = ', '.join(destinatarios)

        destinatarios_finais = [email_usuario] + destinatarios

        body = f"""
        <html>
            <head>{css_hover}</head>
            <body>
                <div class="email-wrapper">
                    <div class="email-card">
                        <div class="email-header">
                            <h2>Visitas de Monitoria Pendentes</h2>
                            <p>Monitorias programadas para os próximos dias</p>
                        </div>
                        <div class="email-body">
                            <p>Olá,</p>
                            <p>Segue abaixo lista com visitas de monitoria programadas para os próximos dias.</p>
                        </div>
                        {tabela_html}
                        <div class="email-footer">
                            <p>Este e-mail é gerado automaticamente a partir de informações inseridas na <strong>Polo Trial</strong>.</p>
                            <p>Qualquer dúvida, contate o <strong>time BI - SVRI</strong>.</p>
                        </div>
                    </div>
                </div>
            </body>
        </html>
        """

        msg.attach(MIMEText(body, 'html'))

        with smtplib.SMTP(smtp_server, email_port) as server:
            server.starttls()
            server.login(email_usuario, email_senha)
            server.sendmail(email_usuario, destinatarios_finais, msg.as_string())

        registrar(
            projeto="Push Campo",
            grupo="Monitoria",
            status="ENVIADO",
            destinatarios=destinatarios_finais,
            num_registros=len(monitoria_envio),
        )

    except Exception as e:
        registrar("Push Campo", "Monitoria", "ERRO", observacao=str(e))
        print(f"Erro ao enviar email de monitoria: {str(e)}")

# chamada
enviar_emails_monitoria(monitoria_envio)